class AppStrings {
  static Map<String, String> of(String language) {
    switch (language) {
      case 'Spanish':
        return _es;
      case 'French':
        return _fr;
      case 'Arabic':
        return _ar;
      case 'Turkish':
        return _tr;
      case 'Chinese':
        return _zh;
      default:
        return _en;
    }
  }

  static const Map<String, String> _en = {
    // Nav
    'nav_home': 'Home',
    'nav_notes': 'Notes',
    'nav_dictionary': 'Dictionary',
    'nav_menu': 'Menu',
    // Menu page
    'section_account': 'ACCOUNT',
    'section_app': 'APP',
    'menu_profile': 'Profile',
    'menu_language': 'Language',
    'menu_statistics': 'Statistics',
    'menu_commands': 'Commands',
    'menu_about': 'About Us',
    'menu_contact': 'Contact Us',
    'menu_logout': 'Logout',
    'guest': 'Guest',
    'no_account': 'No account · data not saved',
    'logout_title': 'Log out?',
    'logout_body': 'Your data is safe and will be here when you return.',
    'logout_cancel': 'Cancel',
    'logout_confirm': 'Logout',
    'select_language': 'Select Language',
    // Home page
    'search_hint': 'Search files...',
    'library': 'Library',
    'tap_hint': 'Tap to read • Long press to delete',
    'no_files': 'No files yet.\nTap + to upload.',
    'delete_confirm': 'Delete',
    'cancel': 'Cancel',
    'deleted': 'deleted',
    'remove_library': 'This will remove it from your library.',
    // Notes page
    'notes_title': 'Notes',
    'title_hint': 'Note title (optional)',
    'listening_title': 'Listening for title...',
    'content_hint': 'Speak or type your note here...',
    'saved_notes': 'Saved Notes',
    'save_note': 'Save Note',
    'clear': 'Clear',
    'note_saved': 'Note saved!',
    'no_notes': 'No notes yet. Start speaking or typing!',
    'error_saving': 'Error saving:',
    'add_content': 'Please add some content before saving.',
    'listening_content': 'Listening in',
    // History page
    'history_title': 'History',
    'history_empty': 'No history yet',
    // About / Contact pages
    'about_title': 'About Us',
    'about_subtitle': 'VOX — Voice Command Reader',
    'contact_title': 'Contact Us',
    'contact_subtitle': 'We\'d love to hear from you',
  };

  static const Map<String, String> _es = {
    'nav_home': 'Inicio',
    'nav_notes': 'Notas',
    'nav_dictionary': 'Diccionario',
    'nav_menu': 'Menú',
    'section_account': 'CUENTA',
    'section_app': 'APP',
    'menu_profile': 'Perfil',
    'menu_language': 'Idioma',
    'menu_statistics': 'Estadísticas',
    'menu_commands': 'Comandos',
    'menu_about': 'Sobre nosotros',
    'menu_contact': 'Contáctanos',
    'menu_logout': 'Cerrar sesión',
    'guest': 'Invitado',
    'no_account': 'Sin cuenta · datos no guardados',
    'logout_title': '¿Cerrar sesión?',
    'logout_body': 'Tus datos están seguros y estarán aquí cuando vuelvas.',
    'logout_cancel': 'Cancelar',
    'logout_confirm': 'Cerrar sesión',
    'select_language': 'Seleccionar idioma',
    'search_hint': 'Buscar archivos...',
    'library': 'Biblioteca',
    'tap_hint': 'Toca para leer • Mantén para eliminar',
    'no_files': 'Sin archivos.\nToca + para subir.',
    'delete_confirm': 'Eliminar',
    'cancel': 'Cancelar',
    'deleted': 'eliminado',
    'remove_library': 'Esto lo eliminará de tu biblioteca.',
    'notes_title': 'Notas',
    'title_hint': 'Título (opcional)',
    'listening_title': 'Escuchando título...',
    'content_hint': 'Habla o escribe tu nota aquí...',
    'saved_notes': 'Notas guardadas',
    'save_note': 'Guardar nota',
    'clear': 'Limpiar',
    'note_saved': '¡Nota guardada!',
    'no_notes': 'Sin notas aún. ¡Habla o escribe!',
    'error_saving': 'Error al guardar:',
    'add_content': 'Por favor agrega contenido antes de guardar.',
    'listening_content': 'Escuchando en',
    'history_title': 'Historial',
    'history_empty': 'Sin historial aún',
    'about_title': 'Sobre nosotros',
    'about_subtitle': 'VOX — Lector por voz',
    'contact_title': 'Contáctanos',
    'contact_subtitle': 'Nos encantaría saber de ti',
  };

  static const Map<String, String> _fr = {
    'nav_home': 'Accueil',
    'nav_notes': 'Notes',
    'nav_dictionary': 'Dictionnaire',
    'nav_menu': 'Menu',
    'section_account': 'COMPTE',
    'section_app': 'APP',
    'menu_profile': 'Profil',
    'menu_language': 'Langue',
    'menu_statistics': 'Statistiques',
    'menu_commands': 'Commandes',
    'menu_about': 'À propos',
    'menu_contact': 'Nous contacter',
    'menu_logout': 'Déconnexion',
    'guest': 'Invité',
    'no_account': 'Sans compte · données non sauvegardées',
    'logout_title': 'Se déconnecter ?',
    'logout_body': 'Vos données sont en sécurité et seront là à votre retour.',
    'logout_cancel': 'Annuler',
    'logout_confirm': 'Déconnexion',
    'select_language': 'Choisir la langue',
    'search_hint': 'Rechercher des fichiers...',
    'library': 'Bibliothèque',
    'tap_hint': 'Appuyer pour lire • Appui long pour supprimer',
    'no_files': 'Aucun fichier.\nAppuyez sur + pour importer.',
    'delete_confirm': 'Supprimer',
    'cancel': 'Annuler',
    'deleted': 'supprimé',
    'remove_library': 'Cela le supprimera de votre bibliothèque.',
    'notes_title': 'Notes',
    'title_hint': 'Titre (optionnel)',
    'listening_title': 'Écoute du titre...',
    'content_hint': 'Parlez ou tapez votre note ici...',
    'saved_notes': 'Notes enregistrées',
    'save_note': 'Enregistrer',
    'clear': 'Effacer',
    'note_saved': 'Note enregistrée !',
    'no_notes': 'Aucune note. Commencez à parler ou écrire !',
    'error_saving': 'Erreur lors de la sauvegarde :',
    'add_content': 'Veuillez ajouter du contenu avant de sauvegarder.',
    'listening_content': 'Écoute en',
    'history_title': 'Historique',
    'history_empty': 'Aucun historique pour l\'instant',
    'about_title': 'À propos',
    'about_subtitle': 'VOX — Lecteur vocal',
    'contact_title': 'Nous contacter',
    'contact_subtitle': 'Nous serions ravis d\'avoir de vos nouvelles',
  };

  static const Map<String, String> _ar = {
    'nav_home': 'الرئيسية',
    'nav_notes': 'الملاحظات',
    'nav_dictionary': 'القاموس',
    'nav_menu': 'القائمة',
    'section_account': 'الحساب',
    'section_app': 'التطبيق',
    'menu_profile': 'الملف الشخصي',
    'menu_language': 'اللغة',
    'menu_statistics': 'الإحصائيات',
    'menu_commands': 'الأوامر',
    'menu_about': 'من نحن',
    'menu_contact': 'اتصل بنا',
    'menu_logout': 'تسجيل الخروج',
    'guest': 'ضيف',
    'no_account': 'بدون حساب · البيانات غير محفوظة',
    'logout_title': 'تسجيل الخروج؟',
    'logout_body': 'بياناتك آمنة وستكون هنا عند عودتك.',
    'logout_cancel': 'إلغاء',
    'logout_confirm': 'خروج',
    'select_language': 'اختر اللغة',
    'search_hint': '...ابحث عن ملفات',
    'library': 'المكتبة',
    'tap_hint': 'اضغط للقراءة • اضغط مطولاً للحذف',
    'no_files': 'لا توجد ملفات.\nاضغط + للرفع.',
    'delete_confirm': 'حذف',
    'cancel': 'إلغاء',
    'deleted': 'تم الحذف',
    'remove_library': 'سيتم إزالته من مكتبتك.',
    'notes_title': 'الملاحظات',
    'title_hint': 'عنوان الملاحظة (اختياري)',
    'listening_title': '...جارٍ الاستماع للعنوان',
    'content_hint': '...تحدث أو اكتب ملاحظتك هنا',
    'saved_notes': 'الملاحظات المحفوظة',
    'save_note': 'حفظ الملاحظة',
    'clear': 'مسح',
    'note_saved': '!تم حفظ الملاحظة',
    'no_notes': '!لا توجد ملاحظات بعد. ابدأ بالتحدث أو الكتابة',
    'error_saving': ':خطأ في الحفظ',
    'add_content': 'يرجى إضافة محتوى قبل الحفظ.',
    'listening_content': 'جارٍ الاستماع بـ',
    'history_title': 'السجل',
    'history_empty': 'لا يوجد سجل بعد',
    'about_title': 'من نحن',
    'about_subtitle': 'VOX — قارئ بالأوامر الصوتية',
    'contact_title': 'اتصل بنا',
    'contact_subtitle': 'يسعدنا التواصل معك',
  };

  static const Map<String, String> _tr = {
    'nav_home': 'Ana Sayfa',
    'nav_notes': 'Notlar',
    'nav_dictionary': 'Sözlük',
    'nav_menu': 'Menü',
    'section_account': 'HESAP',
    'section_app': 'UYGULAMA',
    'menu_profile': 'Profil',
    'menu_language': 'Dil',
    'menu_statistics': 'İstatistikler',
    'menu_commands': 'Komutlar',
    'menu_about': 'Hakkımızda',
    'menu_contact': 'Bize Ulaşın',
    'menu_logout': 'Çıkış Yap',
    'guest': 'Misafir',
    'no_account': 'Hesap yok · veriler kaydedilmedi',
    'logout_title': 'Çıkış yapılsın mı?',
    'logout_body': 'Verileriniz güvende, döndüğünüzde burada olacak.',
    'logout_cancel': 'İptal',
    'logout_confirm': 'Çıkış Yap',
    'select_language': 'Dil Seç',
    'search_hint': 'Dosya ara...',
    'library': 'Kütüphane',
    'tap_hint': 'Okumak için dokun • Silmek için uzun bas',
    'no_files': 'Henüz dosya yok.\nYüklemek için + bas.',
    'delete_confirm': 'Sil',
    'cancel': 'İptal',
    'deleted': 'silindi',
    'remove_library': 'Bu, kütüphanenizden kaldırılacak.',
    'notes_title': 'Notlar',
    'title_hint': 'Not başlığı (isteğe bağlı)',
    'listening_title': 'Başlık dinleniyor...',
    'content_hint': 'Notunuzu buraya konuşun veya yazın...',
    'saved_notes': 'Kaydedilen Notlar',
    'save_note': 'Notu Kaydet',
    'clear': 'Temizle',
    'note_saved': 'Not kaydedildi!',
    'no_notes': 'Henüz not yok. Konuşmaya veya yazmaya başlayın!',
    'error_saving': 'Kaydetme hatası:',
    'add_content': 'Kaydetmeden önce içerik ekleyin.',
    'listening_content': 'Dinleniyor:',
    'history_title': 'Geçmiş',
    'history_empty': 'Henüz geçmiş yok',
    'about_title': 'Hakkımızda',
    'about_subtitle': 'VOX — Sesli Komut Okuyucu',
    'contact_title': 'Bize Ulaşın',
    'contact_subtitle': 'Sizden haber almak isteriz',
  };

  static const Map<String, String> _zh = {
    'nav_home': '首页',
    'nav_notes': '笔记',
    'nav_dictionary': '词典',
    'nav_menu': '菜单',
    'section_account': '账户',
    'section_app': '应用',
    'menu_profile': '个人资料',
    'menu_language': '语言',
    'menu_statistics': '统计',
    'menu_commands': '指令',
    'menu_about': '关于我们',
    'menu_contact': '联系我们',
    'menu_logout': '退出登录',
    'guest': '访客',
    'no_account': '未登录 · 数据未保存',
    'logout_title': '退出登录？',
    'logout_body': '您的数据安全，回来后仍在这里。',
    'logout_cancel': '取消',
    'logout_confirm': '退出',
    'select_language': '选择语言',
    'search_hint': '搜索文件...',
    'library': '图书馆',
    'tap_hint': '点击阅读 • 长按删除',
    'no_files': '暂无文件。\n点击 + 上传。',
    'delete_confirm': '删除',
    'cancel': '取消',
    'deleted': '已删除',
    'remove_library': '这将从您的图书馆中移除。',
    'notes_title': '笔记',
    'title_hint': '笔记标题（可选）',
    'listening_title': '正在听取标题...',
    'content_hint': '在此处说话或输入笔记...',
    'saved_notes': '已保存的笔记',
    'save_note': '保存笔记',
    'clear': '清除',
    'note_saved': '笔记已保存！',
    'no_notes': '暂无笔记，开始说话或输入吧！',
    'error_saving': '保存错误：',
    'add_content': '请在保存前添加内容。',
    'listening_content': '正在用以下语言听取：',
    'history_title': '历史记录',
    'history_empty': '暂无历史记录',
    'about_title': '关于我们',
    'about_subtitle': 'VOX — 语音指令阅读器',
    'contact_title': '联系我们',
    'contact_subtitle': '我们期待您的来信',
  };
}
