class AppStrings {
  /// All English keys (source of truth for warm-up translation).
  static Map<String, String> get english => _en;

  static Map<String, String> of(String language) {
    switch (language) {
      case 'Spanish':
        return _es;
      case 'French':
        return _fr;
      case 'Arabic':
        return _ar;
      case 'Turkish':
        return _tr;
      case 'Chinese':
        return _zh;
      default:
        return _en;
    }
  }

  static const Map<String, String> _en = {
    // Nav
    'nav_home': 'Home',
    'nav_notes': 'Notes',
    'nav_dictionary': 'Dictionary',
    'nav_menu': 'Menu',
    // Menu page
    'section_account': 'ACCOUNT',
    'section_app': 'APP',
    'menu_profile': 'Profile',
    'menu_language': 'Language',
    'menu_statistics': 'Statistics',
    'menu_commands': 'Commands',
    'menu_about': 'About Us',
    'menu_contact': 'Contact Us',
    'menu_logout': 'Logout',
    'guest': 'Guest',
    'no_account': 'No account · data not saved',
    'logout_title': 'Log out?',
    'logout_body': 'Your data is safe and will be here when you return.',
    'logout_cancel': 'Cancel',
    'logout_confirm': 'Logout',
    'select_language': 'Select Language',
    // Home page
    'search_hint': 'Search files...',
    'library': 'Library',
    'tap_hint': 'Tap to read • Long press to delete',
    'no_files': 'No files yet.\nTap + to upload.',
    'delete_confirm': 'Delete',
    'cancel': 'Cancel',
    'deleted': 'deleted',
    'remove_library': 'This will remove it from your library.',
    // Notes page
    'notes_title': 'Notes',
    'voice_notes_title': 'Voice Notes',
    'title_hint': 'Note title (optional)',
    'listening_title': 'Listening for title...',
    'content_hint': 'Speak or type your note here...',
    'saved_notes': 'Saved Notes',
    'save_note': 'Save Note',
    'clear': 'Clear',
    'note_saved': 'Note saved!',
    'no_notes': 'No notes yet. Start speaking or typing!',
    'error_saving': 'Error saving:',
    'add_content': 'Please add some content before saving.',
    'listening_content': 'Listening in',
    // History page
    'history_title': 'History',
    'history_empty': 'No history yet',
    // About / Contact pages
    'about_title': 'About Us',
    'about_subtitle': 'VOX — Voice Command Reader',
    'contact_title': 'Contact Us',
    'contact_subtitle': 'We\'d love to hear from you',
    // Splash / session
    'welcome_back': 'Welcome back.',
    'welcome_back_user': 'Welcome back, {name}.',
    'continuing_guest': 'Continuing as guest.',
    'device_recognized': 'Device recognized.',
    'browser_recognized': 'Browser session recognized.',
    // Notes / recordings
    'guest_badge': 'GUEST',
    'saved_badge': 'SAVED',
    'discard': 'Discard',
    'update_note': 'Update Note',
    'recording_complete': 'Recording complete',
    'save_note_list_hint': 'Tap Save Note below to add this recording to your list.',
    'uploading_audio': 'Uploading audio...',
    'transcribing_audio': 'Transcribing audio...',
    'transcription_complete': 'Transcription complete. Review and save your note.',
    'mic_permission_required': 'Microphone permission is required to record.',
    'title_before_record': 'Please add a title before recording.',
    'record_before_save': 'Please record audio before saving.',
    'title_before_save': 'Please add a title before saving.',
    'search_recordings': 'Search recordings by title...',
    'transcript_edit_hint': 'Transcript appears here. Edit if needed...',
    'note_title_field_hint': 'Note title...',
    'delete_note_title': 'Delete Note?',
    'delete_note_body':
        'This item will be stored in the Recycle Bin and permanently deleted after 30 days.',
    'transcript_updated': 'Transcript updated.',
    'transcription_failed': 'Transcription failed:',
    'could_not_play_audio': 'Could not play audio:',
    'note_deleted': 'Note deleted.',
    'delete': 'Delete',
    'generate': 'Generate',
    'sign_in_cloud_hint':
        'Sign in required for cloud upload/transcription. Recording kept locally.',
    'guest_note_saved': 'Note saved temporarily. Create an account to keep it.',
    'required': 'Required',
    'too_short': 'Too short',
  };

  static const Map<String, String> _es = {
    'nav_home': 'Inicio',
    'nav_notes': 'Notas',
    'nav_dictionary': 'Diccionario',
    'nav_menu': 'Menú',
    'section_account': 'CUENTA',
    'section_app': 'APP',
    'menu_profile': 'Perfil',
    'menu_language': 'Idioma',
    'menu_statistics': 'Estadísticas',
    'menu_commands': 'Comandos',
    'menu_about': 'Sobre nosotros',
    'menu_contact': 'Contáctanos',
    'menu_logout': 'Cerrar sesión',
    'guest': 'Invitado',
    'no_account': 'Sin cuenta · datos no guardados',
    'logout_title': '¿Cerrar sesión?',
    'logout_body': 'Tus datos están seguros y estarán aquí cuando vuelvas.',
    'logout_cancel': 'Cancelar',
    'logout_confirm': 'Cerrar sesión',
    'select_language': 'Seleccionar idioma',
    'search_hint': 'Buscar archivos...',
    'library': 'Biblioteca',
    'tap_hint': 'Toca para leer • Mantén para eliminar',
    'no_files': 'Sin archivos.\nToca + para subir.',
    'delete_confirm': 'Eliminar',
    'cancel': 'Cancelar',
    'deleted': 'eliminado',
    'remove_library': 'Esto lo eliminará de tu biblioteca.',
    'notes_title': 'Notas',
    'voice_notes_title': 'Notas de voz',
    'title_hint': 'Título (opcional)',
    'listening_title': 'Escuchando título...',
    'content_hint': 'Habla o escribe tu nota aquí...',
    'saved_notes': 'Notas guardadas',
    'save_note': 'Guardar nota',
    'clear': 'Limpiar',
    'note_saved': '¡Nota guardada!',
    'no_notes': 'Sin notas aún. ¡Habla o escribe!',
    'error_saving': 'Error al guardar:',
    'add_content': 'Por favor agrega contenido antes de guardar.',
    'listening_content': 'Escuchando en',
    'history_title': 'Historial',
    'history_empty': 'Sin historial aún',
    'about_title': 'Sobre nosotros',
    'about_subtitle': 'VOX — Lector por voz',
    'contact_title': 'Contáctanos',
    'contact_subtitle': 'Nos encantaría saber de ti',
    'welcome_back': 'Bienvenido de nuevo.',
    'welcome_back_user': 'Bienvenido de nuevo, {name}.',
    'continuing_guest': 'Continuando como invitado.',
    'device_recognized': 'Dispositivo reconocido.',
    'browser_recognized': 'Sesión del navegador reconocida.',
    'guest_badge': 'INVITADO',
    'saved_badge': 'GUARDADO',
    'discard': 'Descartar',
    'update_note': 'Actualizar nota',
    'recording_complete': 'Grabación completa',
    'save_note_list_hint': 'Toca Guardar nota abajo para añadir esta grabación a tu lista.',
    'uploading_audio': 'Subiendo audio...',
    'transcribing_audio': 'Transcribiendo audio...',
    'transcription_complete': 'Transcripción lista. Revisa y guarda tu nota.',
    'mic_permission_required': 'Se requiere permiso de micrófono para grabar.',
    'title_before_record': 'Añade un título antes de grabar.',
    'record_before_save': 'Graba audio antes de guardar.',
    'title_before_save': 'Añade un título antes de guardar.',
    'search_recordings': 'Buscar grabaciones por título...',
    'transcript_edit_hint': 'La transcripción aparece aquí. Edítala si quieres...',
    'note_title_field_hint': 'Título de la nota...',
    'delete_note_title': '¿Eliminar nota?',
    'delete_note_body':
        'Este elemento irá a la papelera y se eliminará permanentemente después de 30 días.',
    'transcript_updated': 'Transcripción actualizada.',
    'transcription_failed': 'Error de transcripción:',
    'could_not_play_audio': 'No se pudo reproducir el audio:',
    'note_deleted': 'Nota eliminada.',
    'delete': 'Eliminar',
    'generate': 'Generar',
    'sign_in_cloud_hint':
        'Inicia sesión para subir/transcribir en la nube. La grabación se guardó localmente.',
    'guest_note_saved': 'Nota guardada temporalmente. Crea una cuenta para conservarla.',
    'required': 'Obligatorio',
    'too_short': 'Demasiado corto',
  };

  static const Map<String, String> _fr = {
    'nav_home': 'Accueil',
    'nav_notes': 'Notes',
    'nav_dictionary': 'Dictionnaire',
    'nav_menu': 'Menu',
    'section_account': 'COMPTE',
    'section_app': 'APP',
    'menu_profile': 'Profil',
    'menu_language': 'Langue',
    'menu_statistics': 'Statistiques',
    'menu_commands': 'Commandes',
    'menu_about': 'À propos',
    'menu_contact': 'Nous contacter',
    'menu_logout': 'Déconnexion',
    'guest': 'Invité',
    'no_account': 'Sans compte · données non sauvegardées',
    'logout_title': 'Se déconnecter ?',
    'logout_body': 'Vos données sont en sécurité et seront là à votre retour.',
    'logout_cancel': 'Annuler',
    'logout_confirm': 'Déconnexion',
    'select_language': 'Choisir la langue',
    'search_hint': 'Rechercher des fichiers...',
    'library': 'Bibliothèque',
    'tap_hint': 'Appuyer pour lire • Appui long pour supprimer',
    'no_files': 'Aucun fichier.\nAppuyez sur + pour importer.',
    'delete_confirm': 'Supprimer',
    'cancel': 'Annuler',
    'deleted': 'supprimé',
    'remove_library': 'Cela le supprimera de votre bibliothèque.',
    'notes_title': 'Notes',
    'voice_notes_title': 'Notes vocales',
    'title_hint': 'Titre (optionnel)',
    'listening_title': 'Écoute du titre...',
    'content_hint': 'Parlez ou tapez votre note ici...',
    'saved_notes': 'Notes enregistrées',
    'save_note': 'Enregistrer',
    'clear': 'Effacer',
    'note_saved': 'Note enregistrée !',
    'no_notes': 'Aucune note. Commencez à parler ou écrire !',
    'error_saving': 'Erreur lors de la sauvegarde :',
    'add_content': 'Veuillez ajouter du contenu avant de sauvegarder.',
    'listening_content': 'Écoute en',
    'history_title': 'Historique',
    'history_empty': 'Aucun historique pour l\'instant',
    'about_title': 'À propos',
    'about_subtitle': 'VOX — Lecteur vocal',
    'contact_title': 'Nous contacter',
    'contact_subtitle': 'Nous serions ravis d\'avoir de vos nouvelles',
    'welcome_back': 'Bon retour.',
    'welcome_back_user': 'Bon retour, {name}.',
    'continuing_guest': 'Mode invité.',
    'device_recognized': 'Appareil reconnu.',
    'browser_recognized': 'Session navigateur reconnue.',
    'guest_badge': 'INVITÉ',
    'saved_badge': 'ENREGISTRÉ',
    'discard': 'Annuler',
    'update_note': 'Mettre à jour',
    'recording_complete': 'Enregistrement terminé',
    'save_note_list_hint': 'Appuyez sur Enregistrer ci-dessous pour ajouter cet enregistrement.',
    'uploading_audio': 'Téléversement audio...',
    'transcribing_audio': 'Transcription en cours...',
    'transcription_complete': 'Transcription terminée. Vérifiez et enregistrez.',
    'mic_permission_required': 'Le micro est requis pour enregistrer.',
    'title_before_record': 'Ajoutez un titre avant d\'enregistrer.',
    'record_before_save': 'Enregistrez de l\'audio avant de sauvegarder.',
    'title_before_save': 'Ajoutez un titre avant de sauvegarder.',
    'search_recordings': 'Rechercher des enregistrements...',
    'transcript_edit_hint': 'La transcription s\'affiche ici. Modifiez si besoin...',
    'note_title_field_hint': 'Titre de la note...',
    'delete_note_title': 'Supprimer la note ?',
    'delete_note_body':
        'Cet élément ira dans la corbeille et sera supprimé après 30 jours.',
    'transcript_updated': 'Transcription mise à jour.',
    'transcription_failed': 'Échec de la transcription :',
    'could_not_play_audio': 'Impossible de lire l\'audio :',
    'note_deleted': 'Note supprimée.',
    'delete': 'Supprimer',
    'generate': 'Générer',
    'sign_in_cloud_hint':
        'Connexion requise pour le cloud. Enregistrement conservé localement.',
    'guest_note_saved': 'Note temporaire. Créez un compte pour la garder.',
    'required': 'Requis',
    'too_short': 'Trop court',
  };

  static const Map<String, String> _ar = {
    'nav_home': 'الرئيسية',
    'nav_notes': 'الملاحظات',
    'nav_dictionary': 'القاموس',
    'nav_menu': 'القائمة',
    'section_account': 'الحساب',
    'section_app': 'التطبيق',
    'menu_profile': 'الملف الشخصي',
    'menu_language': 'اللغة',
    'menu_statistics': 'الإحصائيات',
    'menu_commands': 'الأوامر',
    'menu_about': 'من نحن',
    'menu_contact': 'اتصل بنا',
    'menu_logout': 'تسجيل الخروج',
    'guest': 'ضيف',
    'no_account': 'بدون حساب · البيانات غير محفوظة',
    'logout_title': 'تسجيل الخروج؟',
    'logout_body': 'بياناتك آمنة وستكون هنا عند عودتك.',
    'logout_cancel': 'إلغاء',
    'logout_confirm': 'خروج',
    'select_language': 'اختر اللغة',
    'search_hint': '...ابحث عن ملفات',
    'library': 'المكتبة',
    'tap_hint': 'اضغط للقراءة • اضغط مطولاً للحذف',
    'no_files': 'لا توجد ملفات.\nاضغط + للرفع.',
    'delete_confirm': 'حذف',
    'cancel': 'إلغاء',
    'deleted': 'تم الحذف',
    'remove_library': 'سيتم إزالته من مكتبتك.',
    'notes_title': 'الملاحظات',
    'voice_notes_title': 'ملاحظات صوتية',
    'title_hint': 'عنوان الملاحظة (اختياري)',
    'listening_title': '...جارٍ الاستماع للعنوان',
    'content_hint': '...تحدث أو اكتب ملاحظتك هنا',
    'saved_notes': 'الملاحظات المحفوظة',
    'save_note': 'حفظ الملاحظة',
    'clear': 'مسح',
    'note_saved': '!تم حفظ الملاحظة',
    'no_notes': '!لا توجد ملاحظات بعد. ابدأ بالتحدث أو الكتابة',
    'error_saving': ':خطأ في الحفظ',
    'add_content': 'يرجى إضافة محتوى قبل الحفظ.',
    'listening_content': 'جارٍ الاستماع بـ',
    'history_title': 'السجل',
    'history_empty': 'لا يوجد سجل بعد',
    'about_title': 'من نحن',
    'about_subtitle': 'VOX — قارئ بالأوامر الصوتية',
    'contact_title': 'اتصل بنا',
    'contact_subtitle': 'يسعدنا التواصل معك',
    'welcome_back': 'مرحباً بعودتك.',
    'welcome_back_user': 'مرحباً بعودتك، {name}.',
    'continuing_guest': 'المتابعة كضيف.',
    'device_recognized': 'تم التعرف على الجهاز.',
    'browser_recognized': 'تم التعرف على جلسة المتصفح.',
    'guest_badge': 'ضيف',
    'saved_badge': 'محفوظ',
    'discard': 'تجاهل',
    'update_note': 'تحديث الملاحظة',
    'recording_complete': 'اكتمل التسجيل',
    'save_note_list_hint': 'اضغط حفظ الملاحظة أدناه لإضافة هذا التسجيل إلى قائمتك.',
    'uploading_audio': 'جارٍ رفع الصوت...',
    'transcribing_audio': 'جارٍ تحويل الصوت إلى نص...',
    'transcription_complete': 'اكتملت التفريغ. راجع واحفظ ملاحظتك.',
    'mic_permission_required': 'إذن الميكروفون مطلوب للتسجيل.',
    'title_before_record': 'أضف عنواناً قبل التسجيل.',
    'record_before_save': 'سجّل صوتاً قبل الحفظ.',
    'title_before_save': 'أضف عنواناً قبل الحفظ.',
    'search_recordings': 'البحث في التسجيلات بالعنوان...',
    'transcript_edit_hint': 'يظهر النص هنا. يمكنك تعديله...',
    'note_title_field_hint': 'عنوان الملاحظة...',
    'delete_note_title': 'حذف الملاحظة؟',
    'delete_note_body': 'سيُنقل العنصر إلى سلة المحذوفات ويُحذف نهائياً بعد 30 يوماً.',
    'transcript_updated': 'تم تحديث النص.',
    'transcription_failed': 'فشل التفريغ:',
    'could_not_play_audio': 'تعذر تشغيل الصوت:',
    'note_deleted': 'تم حذف الملاحظة.',
    'delete': 'حذف',
    'generate': 'إنشاء',
    'sign_in_cloud_hint': 'يلزم تسجيل الدخول للسحابة. التسجيل محفوظ محلياً.',
    'guest_note_saved': 'حُفظت الملاحظة مؤقتاً. أنشئ حساباً للاحتفاظ بها.',
    'required': 'مطلوب',
    'too_short': 'قصير جداً',
  };

  static const Map<String, String> _tr = {
    'nav_home': 'Ana Sayfa',
    'nav_notes': 'Notlar',
    'nav_dictionary': 'Sözlük',
    'nav_menu': 'Menü',
    'section_account': 'HESAP',
    'section_app': 'UYGULAMA',
    'menu_profile': 'Profil',
    'menu_language': 'Dil',
    'menu_statistics': 'İstatistikler',
    'menu_commands': 'Komutlar',
    'menu_about': 'Hakkımızda',
    'menu_contact': 'Bize Ulaşın',
    'menu_logout': 'Çıkış Yap',
    'guest': 'Misafir',
    'no_account': 'Hesap yok · veriler kaydedilmedi',
    'logout_title': 'Çıkış yapılsın mı?',
    'logout_body': 'Verileriniz güvende, döndüğünüzde burada olacak.',
    'logout_cancel': 'İptal',
    'logout_confirm': 'Çıkış Yap',
    'select_language': 'Dil Seç',
    'search_hint': 'Dosya ara...',
    'library': 'Kütüphane',
    'tap_hint': 'Okumak için dokun • Silmek için uzun bas',
    'no_files': 'Henüz dosya yok.\nYüklemek için + bas.',
    'delete_confirm': 'Sil',
    'cancel': 'İptal',
    'deleted': 'silindi',
    'remove_library': 'Bu, kütüphanenizden kaldırılacak.',
    'notes_title': 'Notlar',
    'voice_notes_title': 'Sesli Notlar',
    'title_hint': 'Not başlığı (isteğe bağlı)',
    'listening_title': 'Başlık dinleniyor...',
    'content_hint': 'Notunuzu buraya konuşun veya yazın...',
    'saved_notes': 'Kaydedilen Notlar',
    'save_note': 'Notu Kaydet',
    'clear': 'Temizle',
    'note_saved': 'Not kaydedildi!',
    'no_notes': 'Henüz not yok. Konuşmaya veya yazmaya başlayın!',
    'error_saving': 'Kaydetme hatası:',
    'add_content': 'Kaydetmeden önce içerik ekleyin.',
    'listening_content': 'Dinleniyor:',
    'history_title': 'Geçmiş',
    'history_empty': 'Henüz geçmiş yok',
    'about_title': 'Hakkımızda',
    'about_subtitle': 'VOX — Sesli Komut Okuyucu',
    'contact_title': 'Bize Ulaşın',
    'contact_subtitle': 'Sizden haber almak isteriz',
    'welcome_back': 'Tekrar hoş geldiniz.',
    'welcome_back_user': 'Tekrar hoş geldiniz, {name}.',
    'continuing_guest': 'Misafir olarak devam ediliyor.',
    'device_recognized': 'Cihaz tanındı.',
    'browser_recognized': 'Tarayıcı oturumu tanındı.',
    'guest_badge': 'MİSAFİR',
    'saved_badge': 'KAYITLI',
    'discard': 'Vazgeç',
    'update_note': 'Notu Güncelle',
    'recording_complete': 'Kayıt tamamlandı',
    'save_note_list_hint': 'Bu kaydı listeye eklemek için aşağıdan Notu Kaydet\'e dokunun.',
    'uploading_audio': 'Ses yükleniyor...',
    'transcribing_audio': 'Ses yazıya dönüştürülüyor...',
    'transcription_complete': 'Döküm tamam. Notunuzu gözden geçirip kaydedin.',
    'mic_permission_required': 'Kayıt için mikrofon izni gerekli.',
    'title_before_record': 'Kayıttan önce bir başlık ekleyin.',
    'record_before_save': 'Kaydetmeden önce ses kaydedin.',
    'title_before_save': 'Kaydetmeden önce bir başlık ekleyin.',
    'search_recordings': 'Kayıtlarda başlığa göre ara...',
    'transcript_edit_hint': 'Döküm burada görünür. Düzenleyebilirsiniz...',
    'note_title_field_hint': 'Not başlığı...',
    'delete_note_title': 'Not silinsin mi?',
    'delete_note_body':
        'Öğe Geri Dönüşüm Kutusu\'na gider ve 30 gün sonra kalıcı olarak silinir.',
    'transcript_updated': 'Döküm güncellendi.',
    'transcription_failed': 'Döküm başarısız:',
    'could_not_play_audio': 'Ses oynatılamadı:',
    'note_deleted': 'Not silindi.',
    'delete': 'Sil',
    'generate': 'Oluştur',
    'sign_in_cloud_hint':
        'Bulut için giriş gerekli. Kayıt yerelde tutuldu.',
    'guest_note_saved': 'Not geçici kaydedildi. Saklamak için hesap oluşturun.',
    'required': 'Zorunlu',
    'too_short': 'Çok kısa',
  };

  static const Map<String, String> _zh = {
    'nav_home': '首页',
    'nav_notes': '笔记',
    'nav_dictionary': '词典',
    'nav_menu': '菜单',
    'section_account': '账户',
    'section_app': '应用',
    'menu_profile': '个人资料',
    'menu_language': '语言',
    'menu_statistics': '统计',
    'menu_commands': '指令',
    'menu_about': '关于我们',
    'menu_contact': '联系我们',
    'menu_logout': '退出登录',
    'guest': '访客',
    'no_account': '未登录 · 数据未保存',
    'logout_title': '退出登录？',
    'logout_body': '您的数据安全，回来后仍在这里。',
    'logout_cancel': '取消',
    'logout_confirm': '退出',
    'select_language': '选择语言',
    'search_hint': '搜索文件...',
    'library': '图书馆',
    'tap_hint': '点击阅读 • 长按删除',
    'no_files': '暂无文件。\n点击 + 上传。',
    'delete_confirm': '删除',
    'cancel': '取消',
    'deleted': '已删除',
    'remove_library': '这将从您的图书馆中移除。',
    'notes_title': '笔记',
    'voice_notes_title': '语音笔记',
    'title_hint': '笔记标题（可选）',
    'listening_title': '正在听取标题...',
    'content_hint': '在此处说话或输入笔记...',
    'saved_notes': '已保存的笔记',
    'save_note': '保存笔记',
    'clear': '清除',
    'note_saved': '笔记已保存！',
    'no_notes': '暂无笔记，开始说话或输入吧！',
    'error_saving': '保存错误：',
    'add_content': '请在保存前添加内容。',
    'listening_content': '正在用以下语言听取：',
    'history_title': '历史记录',
    'history_empty': '暂无历史记录',
    'about_title': '关于我们',
    'about_subtitle': 'VOX — 语音指令阅读器',
    'contact_title': '联系我们',
    'contact_subtitle': '我们期待您的来信',
    'welcome_back': '欢迎回来。',
    'welcome_back_user': '欢迎回来，{name}。',
    'continuing_guest': '以访客身份继续。',
    'device_recognized': '已识别设备。',
    'browser_recognized': '已识别浏览器会话。',
    'guest_badge': '访客',
    'saved_badge': '已保存',
    'discard': '丢弃',
    'update_note': '更新笔记',
    'recording_complete': '录音完成',
    'save_note_list_hint': '点击下方保存笔记，将此录音加入列表。',
    'uploading_audio': '正在上传音频...',
    'transcribing_audio': '正在转写音频...',
    'transcription_complete': '转写完成。请检查并保存笔记。',
    'mic_permission_required': '录音需要麦克风权限。',
    'title_before_record': '录音前请添加标题。',
    'record_before_save': '保存前请先录音。',
    'title_before_save': '保存前请添加标题。',
    'search_recordings': '按标题搜索录音...',
    'transcript_edit_hint': '转写文本显示在此，可编辑...',
    'note_title_field_hint': '笔记标题...',
    'delete_note_title': '删除笔记？',
    'delete_note_body': '该项目将移入回收站，30天后永久删除。',
    'transcript_updated': '转写已更新。',
    'transcription_failed': '转写失败：',
    'could_not_play_audio': '无法播放音频：',
    'note_deleted': '笔记已删除。',
    'delete': '删除',
    'generate': '生成',
    'sign_in_cloud_hint': '云上传/转写需要登录。录音已保存在本地。',
    'guest_note_saved': '笔记已临时保存。创建账户以保留。',
    'required': '必填',
    'too_short': '太短',
  };
}
