class AppStrings {
  /// All English keys (source of truth for warm-up translation).
  static Map<String, String> get english => _en;

  static Map<String, String> of(String language) {
    switch (language) {
      case 'Spanish':
        return _es;
      case 'French':
        return _fr;
      case 'Arabic':
        return _ar;
      case 'Turkish':
        return _tr;
      case 'Chinese':
        return _zh;
      default:
        return _en;
    }
  }

  static const Map<String, String> _en = {
    // Nav
    'nav_home': 'Home',
    'nav_notes': 'Notes',
    'nav_dictionary': 'Dictionary',
    'nav_menu': 'Menu',
    // Menu page
    'section_account': 'ACCOUNT',
    'section_app': 'APP',
    'menu_profile': 'Profile',
    'profile_security_title': 'Account security',
    'profile_change_email': 'Change email',
    'profile_change_email_subtitle':
        'Update sign-in email & password — choose to keep or clear your data',
    'profile_change_password': 'Change password',
    'profile_change_password_subtitle':
        'Secure email link to set a new password',
    'profile_reset_password_email': 'Send password reset email',
    'profile_signed_in_with': 'Signed in with',
    'profile_google_password_hint':
        'You use Google sign-in. Use Change email above, or reset your Google account password in your device settings.',
    'profile_new_email': 'New email address',
    'profile_current_password': 'Current password',
    'profile_new_password': 'New password',
    'profile_confirm_password': 'Confirm new password',
    'profile_confirm_with_google': 'Confirm with Google',
    'profile_email_change_sent':
        'Verification email sent. Open the link in your inbox to finish updating your email.',
    'profile_password_updated': 'Password updated successfully.',
    'profile_passwords_dont_match': 'New passwords do not match.',
    'profile_enter_current_password': 'Enter your current password to continue.',
    'profile_current_email': 'Current email address',
    'profile_verify_continue': 'Verify & continue',
    'profile_got_it': 'Got it',
    'profile_email_step_verify': 'Step 1 of 2 — Verify it\'s you',
    'profile_email_step_new': 'Step 2 of 2 — New sign-in details',
    'profile_email_verify_info':
        'For your security, enter the email and password you use to sign in today. Nothing changes until you finish all steps.',
    'profile_email_new_info':
        'Your new password takes effect right away. We will also email a verification link to your new address — open it to complete the email switch.',
    'profile_email_need_password_account':
        'Change email is only available for email & password accounts. Use Change password first to set one up via the reset link.',
    'profile_email_sync_title': 'What should happen to your data?',
    'profile_email_sync_intro':
        'You are switching to {email}. Choose one option below — this cannot be changed after you continue.',
    'profile_email_sync_keep_title': 'Keep my data',
    'profile_email_sync_keep_body':
        '• Notes, library, commands & recycle bin stay on this account\n'
        '• New saves use your new email after you verify it\n'
        '• Your old email stops working once verification completes',
    'profile_email_sync_fresh_title': 'Start fresh',
    'profile_email_sync_fresh_body':
        '• Permanently deletes all cloud notes, library, commands & recycle bin\n'
        '• Cannot be undone\n'
        '• You begin with an empty account under the new email',
    'profile_email_sync_now': 'Keep my data',
    'profile_email_start_fresh': 'Start fresh',
    'profile_email_fresh_confirm_title': 'Delete all cloud data?',
    'profile_email_fresh_confirm_body':
        'This permanently removes every note, library file, custom command, and recycle-bin item tied to this account. You will start with a blank slate under your new email. This action cannot be undone.',
    'profile_email_fresh_confirm_button': 'Yes, delete everything',
    'profile_email_success_sync_title': 'Almost done — check your inbox',
    'profile_email_success_sync_body':
        '• Your new password is already active\n'
        '• Your notes, library & commands are still here\n'
        '• Open the verification email sent to {email} to finish switching your sign-in address\n'
        '• Until you verify, sign in with your old email',
    'profile_email_success_fresh_title': 'Fresh start — verify your new email',
    'profile_email_success_fresh_body':
        '• All previous cloud data on this account was permanently deleted\n'
        '• Your new password is already active\n'
        '• Open the verification email sent to {email} to activate your new sign-in address',
    'profile_password_reset_hint':
        'Enter the email on your account. We will send a secure link — your current password keeps working until you set a new one through that link.',
    'profile_password_steps':
        '1. Check your inbox (and spam)\n2. Tap the reset link\n3. Choose a new password\n4. Sign in with that new password',
    'profile_password_confirm_title': 'Send password reset email?',
    'profile_password_confirm_body':
        'A secure link will be sent to {email}. Your current password still works until you complete the link and save a new password.',
    'profile_password_sent_title': 'Reset email sent',
    'profile_password_sent_body':
        'We sent a password reset link to {email}. Follow the steps in that email. Your current password remains valid until you finish.',
    'profile_send_reset_email': 'Send reset email',
    'guest_save_sync_title': 'This email already has a Vox account',
    'guest_save_sync_intro':
        'Choose what happens to cloud data for {email}. Your guest session items will be saved to the account you sign into.',
    'guest_save_sync_keep_title': 'Keep my cloud data',
    'guest_save_sync_keep_body':
        '• Restore notes, library & commands from your account\n'
        '• Guest session items are added on top',
    'guest_save_sync_fresh_title': 'Start fresh',
    'guest_save_sync_fresh_body':
        '• Permanently deletes existing cloud data for this account\n'
        '• Only your current guest session is saved',
    'guest_save_fresh_confirm_title': 'Delete existing cloud data?',
    'guest_save_fresh_confirm_body':
        'All notes, library files, and commands already saved under this email will be permanently deleted. Your current guest session will still be uploaded.',
    'guest_save_success_sync': 'Welcome back! Your data is synced and saving.',
    'guest_save_success_fresh': 'Account ready. Starting with a clean cloud library.',
    'guest_save_success_new': 'Account created! Your guest items are now saved.',
    'menu_language': 'Language',
    'menu_statistics': 'Statistics',
    'menu_reminders': 'Reminders',
    'menu_commands': 'Commands',
    'menu_about': 'About Us',
    'menu_contact': 'Contact Us',
    'menu_logout': 'Logout',
    'menu_saved_docs': 'Saved Docs',
    'saved_docs_tab_all': 'All',
    'saved_docs_tab_summaries': 'Summaries',
    'saved_docs_tab_qa': 'Q&A',
    'saved_docs_tab_notes': 'Notes',
    'search_by_title': 'Search by title...',
    'no_saved_docs_yet': 'No saved documents yet.\nSave summaries, Q&A, or notes from Home or Notes.',
    'no_saved_docs_match': 'No documents match your search.',
    'delete_saved_doc_title': 'Delete saved document?',
    'delete_saved_doc_body': 'Delete "{title}"? This cannot be undone.',
    'saved_doc_deleted': 'Document deleted.',
    'saved_docs_sign_in_hint': 'Sign in to save and view documents in Saved Docs.',
    'sign_in_required': 'Sign in required',
    'saved_doc_summary': 'Summary',
    'saved_doc_note': 'Note',
    'no_content': 'No content',
    'save_to_saved_docs': 'Save to Saved Docs',
    'saved_to_saved_docs': 'Saved to Menu → Saved Docs',
    'save_note_need_transcript': 'Add or wait for a transcript before saving.',
    'save_transcript_to_docs': 'Save transcript to Saved Docs',
    'bulk_export_saved_docs': 'Export to device',
    'bulk_export_confirm':
        'Export {count} document(s) from "{tab}" as a ZIP file to your device?',
    'bulk_export_done': 'Exported to {path}',
    'bulk_export_failed': 'Export failed. Try again.',
    'bulk_export_empty': 'Nothing to export in this tab.',
    'guest': 'Guest',
    'no_account': 'No account · data not saved',
    'logout_title': 'Log out?',
    'logout_body': 'Your data is safe and will be here when you return.',
    'logout_cancel': 'Cancel',
    'logout_confirm': 'Logout',
    'select_language': 'Select Language',
    // Home page
    'search_hint': 'Search files...',
    'library': 'Library',
    'tap_hint': 'Tap to read • Long press to delete',
    'no_files': 'No files yet.\nTap + to upload.',
    'delete_confirm': 'Delete',
    'cancel': 'Cancel',
    'deleted': 'deleted',
    'remove_library': 'This will remove it from your library.',
    // Notes page
    'notes_title': 'Notes',
    'voice_notes_title': 'Voice Notes',
    'title_hint': 'Note title (optional)',
    'listening_title': 'Listening for title...',
    'content_hint': 'Speak or type your note here...',
    'saved_notes': 'Saved Notes',
    'save_note': 'Save Note',
    'clear': 'Clear',
    'note_saved': 'Note saved!',
    'no_notes': 'No notes yet. Start speaking or typing!',
    'error_saving': 'Error saving:',
    'add_content': 'Please add some content before saving.',
    'listening_content': 'Listening in',
    // History page
    'history_title': 'History',
    'history_empty': 'No history yet',
    // About / Contact pages
    'about_title': 'About Us',
    'about_subtitle': 'VOX — Voice Command Reader',
    'contact_title': 'Contact Us',
    'contact_subtitle': 'We\'d love to hear from you',
    // Splash / session
    'welcome_back': 'Welcome back.',
    'welcome_back_user': 'Welcome back, {name}.',
    'continuing_guest': 'Continuing as guest.',
    'device_recognized': 'Device recognized.',
    'browser_recognized': 'Browser session recognized.',
    // Notes / recordings
    'guest_badge': 'GUEST',
    'saved_badge': 'SAVED',
    'discard': 'Discard',
    'update_note': 'Update Note',
    'recording_complete': 'Recording complete',
    'save_note_list_hint': 'Tap Save Note below to add this recording to your list.',
    'uploading_audio': 'Uploading audio...',
    'transcribing_audio': 'Transcribing audio...',
    'transcription_complete': 'Transcription complete. Review and save your note.',
    'mic_permission_required': 'Microphone permission is required to record.',
    'title_before_record': 'Please add a title before recording.',
    'record_before_save': 'Please record audio before saving.',
    'title_before_save': 'Please add a title before saving.',
    'search_recordings': 'Search recordings by title...',
    'transcript_edit_hint': 'Transcript appears here. Edit if needed...',
    'note_title_field_hint': 'Note title...',
    'delete_note_title': 'Delete Note?',
    'delete_note_body':
        'This item will be stored in the Recycle Bin and permanently deleted after 30 days.',
    'transcript_updated': 'Transcript updated.',
    'transcription_failed': 'Transcription failed:',
    'could_not_play_audio': 'Could not play audio:',
    'note_deleted': 'Note deleted.',
    'delete': 'Delete',
    'generate': 'Generate',
    'sign_in_cloud_hint':
        'Sign in required for cloud upload/transcription. Recording kept locally.',
    'guest_note_saved': 'Note saved temporarily. Create an account to keep it.',
    'required': 'Required',
    'too_short': 'Too short',
    'settings': 'Settings',
    'mic_blocked_settings':
        'Microphone blocked. Enable it in Settings to record voice notes.',
    'mic_denied_settings':
        'Microphone permission denied. Enable it in Settings.',
    'voice_input_notes_only':
        'Voice input is only available on the Voice Notes screen.',
    'recording_notes_only':
        'Recording is only available on the Voice Notes screen.',
    'could_not_start_recording': 'Could not start recording:',
    'no_audio_file_saved':
        'No audio file was saved. Check microphone permission and try again.',
    'upload_failed_after_record':
        'Recording processed, but upload/transcription failed:',
    'sign_in_to_upload':
        'Please sign in with your account to upload recordings.',
    'audio_file_not_found': 'Audio file not found.',
    'recording_too_small':
        'Recording file is too small. The microphone may not have captured audio.',
    'no_voice_detected':
        'No voice detected. Allow microphone access and try again.',
    'transcript_not_generated': 'Transcript could not be generated.',
    'audio_saved_no_transcript':
        'Audio saved. Transcript could not be generated.',
    'upload_transcription_prefix': 'Upload/transcription:',
    'audio_unavailable_device':
        'Audio file is no longer available on this device.',
    'sign_in_to_save': 'Please sign in to save notes to your account.',
    'no_internet_sync': 'No internet. Note will sync when back online.',
    'note_moved_recycle':
        'Note moved to Recycle Bin. Kept for 30 days.',
    'note_moved_recycle_named':
        '"{title}" moved to Recycle Bin. Kept for 30 days.',
    'cannot_delete_offline': 'Cannot delete while offline.',
    'delete_failed': 'Delete failed:',
    'delete_selected_title': 'Delete Selected?',
    'delete_notes_count': 'Delete {count}',
    'notes_deleted_count': '{count} note(s) deleted.',
    'notes_moved_recycle_count':
        '{count} note(s) moved to Recycle Bin. Kept for 30 days.',
    'delete_forever_selected_title': 'Delete Forever?',
    'delete_forever_selected_body':
        '{count} item(s) will be permanently deleted and cannot be recovered.',
    'items_permanently_deleted': '{count} item(s) permanently deleted.',
    'reminders_deleted_count': '{count} reminder(s) deleted.',
    'failed_to_delete': 'Failed to delete:',
    'transcript_empty': 'Transcript cannot be empty.',
    'note_not_found': 'Note not found.',
    'transcript_saved_to': 'Transcript saved to {path}',
    'ai_tools': 'AI Tools',
    'summarize': 'Summarize',
    'qa_generator': 'Q&A Generator',
    'study_buddy': 'Study Buddy',
    'ai_summary': 'Summary',
    'read_aloud': 'Read Aloud',
    'stop_speaking': 'Stop',
    'auto_on': 'Auto ON',
    'auto_off': 'Auto OFF',
    'card_progress': 'Card {current} of {total}',
    'tap_to_flip': 'Tap to flip',
    'flashcard_question': 'QUESTION',
    'flashcard_answer': 'ANSWER',
    'previous_card': '← Previous',
    'next_card': 'Next →',
    'generating_summary': 'Generating summary...',
    'creating_questions': 'Creating {count} questions...',
    'something_went_wrong': 'Something went wrong',
    'try_again': 'Try Again',
    'no_text_to_analyze':
        'No text to analyze. Add content or wait for the voice note transcript.',
    'save_label': 'Save',
    'save_summary_title': 'Save Summary',
    'save_qa_title': 'Save Q&A',
    'title_for_saved_docs': 'Title for Saved Docs:',
    'title_hint_saved_docs': 'e.g. Chapter 1 Biology',
    'sign_in_to_save_docs': 'Please sign in to save to Saved Docs.',
    'saved_to_menu_docs': 'Saved to Menu → Saved Docs',
    'could_not_save_document': 'Could not save document.',
    'speak_question_n': 'Question {n}: {text}',
    'speak_answer': 'Answer: {text}',
    'speak_question': 'Question: {text}',
    'ask_about_document': 'Ask about this document...',
    'study_buddy_greeting':
        'Hi! Ask me anything about this transcript or document.',
    'study_buddy_thinking': 'Thinking...',
    'transcript_not_ready_chat':
        'Transcript is not ready yet. Wait for transcription to finish.',
    'tab_transcript': 'Transcript',
    'tab_audio': 'Audio',
    'edit': 'Edit',
    'updating': 'Updating...',
    'update': 'Update',
    'update_failed': 'Update failed:',
    'no_transcript_yet': 'No transcript yet.',
    'voice_recording': 'Voice Recording',
    'audio_gone_device': 'Audio file is no longer on this device.',
    'no_audio_for_note': 'No audio available for this note.',
    'how_many_questions': 'How many questions?',
    'cards_count': '{count} cards',
    'record': 'Record',
    'recording_time_left': 'Recording · {time} left',
    'recording_audio_hint':
        'Recording audio · playback after you stop',
    'stop_recording': 'Stop Recording',
    'processing_audio': 'Processing audio...',
    'preparing_playback': 'Preparing playback…',
    'transcription_failed_short': 'Transcription failed',
    'audio_saved_locally': 'Audio saved locally',
    'audio_saved_locally_error': 'Audio saved locally. {error}',
    'discard_recording_title': 'Discard recording?',
    'discard_recording_body':
        'This will delete the audio and transcript.',
    'discard_recording_btn': 'Discard recording',
    'transcript_label': 'Transcript',
    'deselect': 'Deselect',
    'select_all': 'Select All',
    'cancel_edit': 'Cancel Edit',
    'selected_count': '{count} selected',
    'chatbot_mic_menu_faqs':
        'Microphone is busy. Stop recording or close another voice panel first.',
    'speech_error': 'Speech error:',
    'speech_not_available':
        'Speech recognition not available. Check permissions.',
    'chatbot_greeting':
        'Hello! I am the Vox Assistant. Ask about Notes, Saved Docs, Reminders, Study Buddy, voice search, Statistics, or any Menu feature.',
    'vox_assistant': 'Vox Assistant',
    'toggle_voice_output': 'Toggle Voice Output',
    'type_message': 'Type a message...',
    'keep': 'Keep',
    'listening_dots': 'Listening...',
    'search_voice_listening': 'Speak to search...',
    'ask_something': 'Ask something...',
    'stop_voice_output': 'Stop Voice Output',
    'add_reminder': 'Add Reminder',
    'pick_reminder_target': 'Choose a file or note',
    'reminder_tab_files': 'Files',
    'reminder_tab_notes': 'Notes',
    'reminder_type_file': 'Library file',
    'reminder_type_note': 'Voice note',
    'reminders_empty_title': 'No reminders yet',
    'reminders_empty_body':
        'Set alarms to study a file or review a note. You will get a phone notification when it is time.',
    'no_reminder_targets': 'No files or notes available yet.',
    'repeat_reminder_title': 'Repeat this reminder?',
    'repeat_reminder_body': 'Choose once or repeat every day at the same time.',
    'reminder_once': 'Once',
    'reminder_daily': 'Every day',
    'reminder_set_for': 'Reminder set for {title} at {time}',
    'reminder_daily_at': 'Every day at {time}',
    'reminder_once_at': '{date} at {time}',
    'delete_reminder_title': 'Delete reminder?',
    'delete_reminder_body': 'This will cancel the scheduled notification.',
    'reminder_deleted': 'Reminder deleted.',
    'edit_reminder_time': 'Edit reminder time',
    'reminder_updated': 'Reminder updated.',
    'reminder_schedule_failed':
        'Could not schedule this reminder. Check notification and alarm permissions.',
    'notification_permission_title': 'Allow notifications',
    'notification_permission_body':
        'Vox needs notification permission to show study reminders in your notification bar and on the lock screen.',
    'exact_alarm_permission_title': 'Allow alarms & reminders',
    'exact_alarm_permission_body':
        'On this device, Vox also needs permission to schedule exact alarms so reminders fire at the time you pick. Tap Continue to open the system screen and turn on "Alarms & reminders" for Vox.',
    'notification_permission_denied':
        'Notifications are off. Turn them on in Settings to get reminders.',
    'exact_alarm_permission_denied':
        'Exact alarms are off. Enable "Alarms & reminders" for Vox in Settings so reminders fire on time.',
    'enable_notifications': 'Enable notifications',
    'reminders_need_permissions':
        'Reminders need notification permission. Tap below to allow it (like the microphone).',
    'session_restore_title': 'Sign in to load your data',
    'session_restore_body':
        'This phone remembers your account, but your secure sign-in session expired. Sign in again to load your library and notes from the cloud.',
    'session_restore_retry': 'Retry',
    'session_restore_sign_in': 'Sign in',
    'firestore_permission_error':
        'Could not load cloud data. Sign in again with the same account you used on this phone.',
    // Assistant (Home)
    'assistant_label': 'Assistant',
    'assistant_mode_tooltip':
        'Assistant — double-tap anywhere to turn on; double-tap again to turn off',
    'assistant_on': 'Assistant on',
    'assistant_off': 'Assistant off',
    // Library folders (Home)
    'folder_all_files': 'All Files',
    'folder_pdfs': 'PDFs',
    'folder_documents': 'Documents',
    'folder_scans': 'Scans',
    // File type labels
    'file_type_note': 'Note',
    'file_type_pdf': 'PDF',
    'file_type_doc': 'DOC',
    'file_type_docx': 'DOCX',
    'file_type_ppt': 'PPT',
    'file_type_pptx': 'PPTX',
    'file_type_txt': 'TXT',
    'file_type_scan': 'Scan',
    'file_type_file': 'File',
    // Dictionary
    'dictionary_search_hint': 'Search any word in your selected language...',
    'dictionary_not_available_chinese': 'Not available in Chinese',
    'dictionary_chinese_unavailable_title': 'Chinese dictionary\nnot available yet',
    'dictionary_chinese_unavailable_body':
        'Switch to English, Spanish, French,\nArabic, or Turkish in the Menu.',
    'dictionary_vox_title': 'VOX Dictionary',
    'dictionary_tagline':
        'General, medical, legal & technical\nall in one search.',
    'dictionary_recent_searches': 'Recent searches (7 days)',
    'dictionary_source_general': 'General',
    'dictionary_source_medical': 'Medical',
    'dictionary_source_legal': 'Legal',
    'dictionary_source_technical': 'Technical',
    'tap_to_speak': 'Tap to speak',
    // Menu
    'section_preferences': 'PREFERENCES',
    'dark_mode': 'Dark Mode',
    'light_mode': 'Light Mode',
    'menu_recommendations': 'Recommendations',
    'menu_recycle_bin': 'Recycle Bin',
    'menu_faqs': 'FAQs',
    'offline_cached_data': 'Offline — showing cached data',
    // Recycle bin
    'recycle_bin_title': 'Recycle Bin',
    'recycle_bin_sign_in_title': 'Sign in to use Recycle Bin',
    'recycle_bin_sign_in_body':
        'The Recycle Bin is for registered users only. Guest data is removed when you leave the app. Create an account to unlock 30-day recovery.',
    'recycle_bin_tab_notes': 'Notes',
    'recycle_bin_tab_recordings': 'Recordings',
    'recycle_bin_tab_uploads': 'Uploads',
    // Recommendations
    'recommendations_title': 'Recommendations',
    'recommendations_headline': 'Help Us Make\nIt Better!',
    'recommendations_subtitle':
        'Your feedback helps us improve\nand build features you\'ll love.',
    'recommendations_rate_title': 'Rate Vox Features',
    'recommendations_rate_subtitle': 'How would you rate your experience so far?',
    'recommendations_suggestions_title': 'Share Your Suggestions',
    'recommendations_suggestions_subtitle': 'What can we improve or add next?',
    'recommendations_hint': 'Write your recommendation here...',
    'recommendations_examples_title': 'Example Suggestions',
    'recommendations_optional': 'This is optional. You can skip and do it later.',
    'recommendations_submit': 'Submit Recommendation',
    'recommendations_skip': 'Skip',
    'recommendations_thank_you': 'Thank You!',
    'recommendations_success':
        'Your recommendation and {rating}-star rating have been submitted successfully.',
    'recommendations_example_1': 'Add offline dictionary lookups',
    'recommendations_example_2': 'Include voice note language translation',
    'recommendations_example_3': 'Allow importing custom flashcard decks',
    // Upload page
    'upload_files_title': 'Upload Files',
    'upload_hero': 'Upload a file or scan a\nphysical document with your camera',
    'upload_reading_starts': 'Reading starts automatically',
    'upload_choose_file': 'CHOOSE FILE',
    'upload_scan_document': 'SCAN DOCUMENT',
    'upload_or': 'OR',
    'upload_guest_notice':
        'You\'re browsing as a guest. Files will only be available until you close the app.',
    'upload_tip_lighting': 'Good lighting improves accuracy',
    'upload_tip_frame': 'Fill the frame with the text and hold camera steady',
    'upload_tip_multipage': 'Multi-page mode merges all pages into one document',
    'upload_supported_types_label':
        'Supported: PDF, Word, PowerPoint, Excel, photos (JPG/PNG), TXT, and more',
    'upload_status_uploading': 'Uploading...',
    'upload_status_reading_file': 'Reading file...',
    'upload_status_extracting_pdf': 'Extracting PDF text...',
    'upload_status_ocr_image': 'Reading text from image...',
    'upload_status_extracting_slides': 'Extracting slide text (ignoring images)...',
    'upload_status_extracting_doc': 'Extracting text (ignoring images)...',
    'upload_status_saving_temp': 'Adding to temporary library...',
    'upload_status_saving_cloud': 'Saving to library...',
    'upload_status_saving_scan': 'Saving scan...',
    'upload_status_scan_page': 'Reading page {current} of {total}...',
    'upload_status_image_n': 'Reading image {current} of {total}...',
    'upload_file_ready': 'File ready. Reading started.',
    'upload_snack_guest': '"{name}" added temporarily. Create an account to save it.',
    'upload_snack_saved': '"{name}" saved & reading started!',
    'upload_snack_no_text': '"{name}" saved — text could not be extracted from this format.',
    'upload_save_cloud_failed':
        'Could not save "{name}" to cloud ({error}). Reading locally.',
    'upload_type_unsupported':
        'File type .{ext} is not supported. Supported types: {types}',
    'upload_too_large_type':
        'File is too large. Maximum size for .{ext} files is {mb}MB.',
    'upload_empty_file': 'Cannot upload empty files.',
    'upload_multi_mixed':
        'Select one document at a time, or select multiple photos only.',
    'upload_read_failed':
        'Could not read this file. Try again or use a smaller file.',
    'upload_too_large_50mb': 'File is too large. Maximum size is 50MB.',
    'upload_failed': 'Upload failed. Please try again.',
    'upload_image_only_photo':
        'This upload only contains images — no text was found to read. Try Scan Document with good lighting, or a clearer photo.',
    'upload_image_only_doc':
        'This upload only contains images — no readable text in "{name}". Embedded pictures are ignored. Add typed text in Word or PowerPoint, or use Scan Document for photo pages.',
    'upload_image_only_voice':
        'This upload only contains images. No text to read aloud.',
    'upload_camera_required': 'Camera permission is required to scan documents.',
    'upload_scan_another': 'Scan another page?',
    'upload_scan_failed': 'Scan failed. Please try again.',
    'upload_images_failed': 'Could not read image(s). Please try again.',
    'home_doc_what_to_do': 'What would you like to do?',
    'home_read_document': 'Read Document',
    'home_read_subtitle': 'Listen to the document read aloud',
    'home_summarize': 'Summarize',
    'home_summarize_subtitle': 'Get an AI-powered summary of the document',
    'home_qa_generator': 'Q&A Generator',
    'home_qa_subtitle': 'Create a study Q&A set from the document',
    'home_library_guest_hint':
        'Tap + to upload.\nFiles are temporary until you create an account.',
    'reader_settings_title': 'Reader Settings',
    'reader_reading_language': 'Reading voice language',
    'reader_reading_language_hint':
        'Match the document language for correct pronunciation',
    'voice_controls_intro_headphones':
        'Earphones on — say pause, play, continue, stop, forward, back, or highlight while the app reads.',
    'voice_controls_intro_speaker':
        'Voice while reading: pause, play, continue, stop, forward, back, highlight. Plug in earphones if commands are missed.',
    'voice_controls_paused_tip':
        'Paused — say play, continue, stop, forward, back, or highlight.',
    'voice_controls_playing_speaker_tip':
        'Say pause, stop, forward, back, or highlight. Earphones work best so the mic hears only you.',
    'voice_controls_playing_headphone_tip':
        'Say pause, play, continue, stop, forward, back, or highlight anytime while reading.',
    'voice_controls_unavailable':
        'Voice controls unavailable — check mic permission.',
  };

  static const Map<String, String> _es = {
    'nav_home': 'Inicio',
    'nav_notes': 'Notas',
    'nav_dictionary': 'Diccionario',
    'nav_menu': 'Menú',
    'section_account': 'CUENTA',
    'section_app': 'APP',
    'menu_profile': 'Perfil',
    'menu_language': 'Idioma',
    'menu_statistics': 'Estadísticas',
    'menu_commands': 'Comandos',
    'menu_about': 'Sobre nosotros',
    'menu_contact': 'Contáctanos',
    'menu_logout': 'Cerrar sesión',
    'guest': 'Invitado',
    'no_account': 'Sin cuenta · datos no guardados',
    'logout_title': '¿Cerrar sesión?',
    'logout_body': 'Tus datos están seguros y estarán aquí cuando vuelvas.',
    'logout_cancel': 'Cancelar',
    'logout_confirm': 'Cerrar sesión',
    'select_language': 'Seleccionar idioma',
    'search_hint': 'Buscar archivos...',
    'library': 'Biblioteca',
    'tap_hint': 'Toca para leer • Mantén para eliminar',
    'no_files': 'Sin archivos.\nToca + para subir.',
    'delete_confirm': 'Eliminar',
    'cancel': 'Cancelar',
    'deleted': 'eliminado',
    'remove_library': 'Esto lo eliminará de tu biblioteca.',
    'notes_title': 'Notas',
    'voice_notes_title': 'Notas de voz',
    'title_hint': 'Título (opcional)',
    'listening_title': 'Escuchando título...',
    'content_hint': 'Habla o escribe tu nota aquí...',
    'saved_notes': 'Notas guardadas',
    'save_note': 'Guardar nota',
    'clear': 'Limpiar',
    'note_saved': '¡Nota guardada!',
    'no_notes': 'Sin notas aún. ¡Habla o escribe!',
    'error_saving': 'Error al guardar:',
    'add_content': 'Por favor agrega contenido antes de guardar.',
    'listening_content': 'Escuchando en',
    'history_title': 'Historial',
    'history_empty': 'Sin historial aún',
    'about_title': 'Sobre nosotros',
    'about_subtitle': 'VOX — Lector por voz',
    'contact_title': 'Contáctanos',
    'contact_subtitle': 'Nos encantaría saber de ti',
    'welcome_back': 'Bienvenido de nuevo.',
    'welcome_back_user': 'Bienvenido de nuevo, {name}.',
    'continuing_guest': 'Continuando como invitado.',
    'device_recognized': 'Dispositivo reconocido.',
    'browser_recognized': 'Sesión del navegador reconocida.',
    'guest_badge': 'INVITADO',
    'saved_badge': 'GUARDADO',
    'discard': 'Descartar',
    'update_note': 'Actualizar nota',
    'recording_complete': 'Grabación completa',
    'save_note_list_hint': 'Toca Guardar nota abajo para añadir esta grabación a tu lista.',
    'uploading_audio': 'Subiendo audio...',
    'transcribing_audio': 'Transcribiendo audio...',
    'transcription_complete': 'Transcripción lista. Revisa y guarda tu nota.',
    'mic_permission_required': 'Se requiere permiso de micrófono para grabar.',
    'title_before_record': 'Añade un título antes de grabar.',
    'record_before_save': 'Graba audio antes de guardar.',
    'title_before_save': 'Añade un título antes de guardar.',
    'search_recordings': 'Buscar grabaciones por título...',
    'transcript_edit_hint': 'La transcripción aparece aquí. Edítala si quieres...',
    'note_title_field_hint': 'Título de la nota...',
    'delete_note_title': '¿Eliminar nota?',
    'delete_note_body':
        'Este elemento irá a la papelera y se eliminará permanentemente después de 30 días.',
    'transcript_updated': 'Transcripción actualizada.',
    'transcription_failed': 'Error de transcripción:',
    'could_not_play_audio': 'No se pudo reproducir el audio:',
    'note_deleted': 'Nota eliminada.',
    'delete': 'Eliminar',
    'generate': 'Generar',
    'sign_in_cloud_hint':
        'Inicia sesión para subir/transcribir en la nube. La grabación se guardó localmente.',
    'guest_note_saved': 'Nota guardada temporalmente. Crea una cuenta para conservarla.',
    'required': 'Obligatorio',
    'too_short': 'Demasiado corto',
    'settings': 'Ajustes',
    'mic_blocked_settings':
        'Micrófono bloqueado. Actívalo en Ajustes para grabar notas de voz.',
    'mic_denied_settings':
        'Permiso de micrófono denegado. Actívalo en Ajustes.',
    'voice_input_notes_only':
        'La entrada de voz solo está disponible en Notas de voz.',
    'recording_notes_only':
        'La grabación solo está disponible en Notas de voz.',
    'could_not_start_recording': 'No se pudo iniciar la grabación:',
    'no_audio_file_saved':
        'No se guardó audio. Comprueba el permiso del micrófono e inténtalo de nuevo.',
    'upload_failed_after_record':
        'Grabación procesada, pero falló la subida/transcripción:',
    'sign_in_to_upload':
        'Inicia sesión con tu cuenta para subir grabaciones.',
    'audio_file_not_found': 'Archivo de audio no encontrado.',
    'recording_too_small':
        'El archivo es demasiado pequeño. El micrófono puede no haber captado audio.',
    'no_voice_detected':
        'No se detectó voz. Permite el micrófono e inténtalo de nuevo.',
    'transcript_not_generated': 'No se pudo generar la transcripción.',
    'audio_saved_no_transcript':
        'Audio guardado. No se pudo generar la transcripción.',
    'upload_transcription_prefix': 'Subida/transcripción:',
    'audio_unavailable_device':
        'El audio ya no está disponible en este dispositivo.',
    'sign_in_to_save': 'Inicia sesión para guardar notas en tu cuenta.',
    'no_internet_sync':
        'Sin internet. La nota se sincronizará cuando vuelva la conexión.',
    'note_moved_recycle':
        'Nota movida a la papelera. Se conserva 30 días.',
    'note_moved_recycle_named':
        '"{title}" movida a la papelera. Se conserva 30 días.',
    'cannot_delete_offline': 'No se puede eliminar sin conexión.',
    'delete_failed': 'Error al eliminar:',
    'delete_selected_title': '¿Eliminar seleccionadas?',
    'delete_notes_count': 'Eliminar {count}',
    'notes_deleted_count': '{count} nota(s) eliminada(s).',
    'failed_to_delete': 'Error al eliminar:',
    'transcript_empty': 'La transcripción no puede estar vacía.',
    'note_not_found': 'Nota no encontrada.',
    'transcript_saved_to': 'Transcripción guardada en {path}',
    'ai_tools': 'Herramientas IA',
    'summarize': 'Resumir',
    'qa_generator': 'Generador de preguntas',
    'study_buddy': 'Compañero de estudio',
    'ask_about_document': 'Pregunta sobre este documento...',
    'study_buddy_greeting':
        '¡Hola! Pregúntame lo que quieras sobre esta transcripción o documento.',
    'study_buddy_thinking': 'Pensando...',
    'transcript_not_ready_chat':
        'La transcripción aún no está lista. Espera a que termine.',
    'tab_transcript': 'Transcripción',
    'tab_audio': 'Audio',
    'edit': 'Editar',
    'updating': 'Actualizando...',
    'update': 'Actualizar',
    'update_failed': 'Error al actualizar:',
    'no_transcript_yet': 'Aún no hay transcripción.',
    'voice_recording': 'Grabación de voz',
    'audio_gone_device': 'El audio ya no está en este dispositivo.',
    'no_audio_for_note': 'No hay audio para esta nota.',
    'how_many_questions': '¿Cuántas preguntas?',
    'cards_count': '{count} tarjetas',
    'record': 'Grabar',
    'recording_time_left': 'Grabando · {time} restante',
    'recording_audio_hint':
        'Grabando audio · reproducción al detener',
    'stop_recording': 'Detener grabación',
    'processing_audio': 'Procesando audio...',
    'preparing_playback': 'Preparando reproducción…',
    'transcription_failed_short': 'Transcripción fallida',
    'audio_saved_locally': 'Audio guardado localmente',
    'audio_saved_locally_error': 'Audio guardado localmente. {error}',
    'discard_recording_title': '¿Descartar grabación?',
    'discard_recording_body':
        'Esto eliminará el audio y la transcripción.',
    'discard_recording_btn': 'Descartar grabación',
    'transcript_label': 'Transcripción',
    'deselect': 'Deseleccionar',
    'select_all': 'Seleccionar todo',
    'cancel_edit': 'Cancelar edición',
    'selected_count': '{count} seleccionadas',
    'chatbot_mic_menu_faqs':
        'El micrófono del chatbot solo está en Menú y Preguntas frecuentes.',
    'speech_error': 'Error de voz:',
    'speech_not_available':
        'Reconocimiento de voz no disponible. Comprueba permisos.',
    'chatbot_greeting':
        '¡Hola! Soy el Asistente Vox. ¿En qué puedo ayudarte hoy?',
    'vox_assistant': 'Asistente Vox',
    'toggle_voice_output': 'Activar/desactivar voz',
    'type_message': 'Escribe un mensaje...',
    'keep': 'Conservar',
    'listening_dots': 'Escuchando...',
    'search_voice_listening': 'Habla para buscar...',
    'ask_something': 'Pregunta algo...',
    'stop_voice_output': 'Detener voz',
  };

  static const Map<String, String> _fr = {
    'nav_home': 'Accueil',
    'nav_notes': 'Notes',
    'nav_dictionary': 'Dictionnaire',
    'nav_menu': 'Menu',
    'section_account': 'COMPTE',
    'section_app': 'APP',
    'menu_profile': 'Profil',
    'menu_language': 'Langue',
    'menu_statistics': 'Statistiques',
    'menu_commands': 'Commandes',
    'menu_about': 'À propos',
    'menu_contact': 'Nous contacter',
    'menu_logout': 'Déconnexion',
    'guest': 'Invité',
    'no_account': 'Sans compte · données non sauvegardées',
    'logout_title': 'Se déconnecter ?',
    'logout_body': 'Vos données sont en sécurité et seront là à votre retour.',
    'logout_cancel': 'Annuler',
    'logout_confirm': 'Déconnexion',
    'select_language': 'Choisir la langue',
    'search_hint': 'Rechercher des fichiers...',
    'library': 'Bibliothèque',
    'tap_hint': 'Appuyer pour lire • Appui long pour supprimer',
    'no_files': 'Aucun fichier.\nAppuyez sur + pour importer.',
    'delete_confirm': 'Supprimer',
    'cancel': 'Annuler',
    'deleted': 'supprimé',
    'remove_library': 'Cela le supprimera de votre bibliothèque.',
    'notes_title': 'Notes',
    'voice_notes_title': 'Notes vocales',
    'title_hint': 'Titre (optionnel)',
    'listening_title': 'Écoute du titre...',
    'content_hint': 'Parlez ou tapez votre note ici...',
    'saved_notes': 'Notes enregistrées',
    'save_note': 'Enregistrer',
    'clear': 'Effacer',
    'note_saved': 'Note enregistrée !',
    'no_notes': 'Aucune note. Commencez à parler ou écrire !',
    'error_saving': 'Erreur lors de la sauvegarde :',
    'add_content': 'Veuillez ajouter du contenu avant de sauvegarder.',
    'listening_content': 'Écoute en',
    'history_title': 'Historique',
    'history_empty': 'Aucun historique pour l\'instant',
    'about_title': 'À propos',
    'about_subtitle': 'VOX — Lecteur vocal',
    'contact_title': 'Nous contacter',
    'contact_subtitle': 'Nous serions ravis d\'avoir de vos nouvelles',
    'welcome_back': 'Bon retour.',
    'welcome_back_user': 'Bon retour, {name}.',
    'continuing_guest': 'Mode invité.',
    'device_recognized': 'Appareil reconnu.',
    'browser_recognized': 'Session navigateur reconnue.',
    'guest_badge': 'INVITÉ',
    'saved_badge': 'ENREGISTRÉ',
    'discard': 'Annuler',
    'update_note': 'Mettre à jour',
    'recording_complete': 'Enregistrement terminé',
    'save_note_list_hint': 'Appuyez sur Enregistrer ci-dessous pour ajouter cet enregistrement.',
    'uploading_audio': 'Téléversement audio...',
    'transcribing_audio': 'Transcription en cours...',
    'transcription_complete': 'Transcription terminée. Vérifiez et enregistrez.',
    'mic_permission_required': 'Le micro est requis pour enregistrer.',
    'title_before_record': 'Ajoutez un titre avant d\'enregistrer.',
    'record_before_save': 'Enregistrez de l\'audio avant de sauvegarder.',
    'title_before_save': 'Ajoutez un titre avant de sauvegarder.',
    'search_recordings': 'Rechercher des enregistrements...',
    'transcript_edit_hint': 'La transcription s\'affiche ici. Modifiez si besoin...',
    'note_title_field_hint': 'Titre de la note...',
    'delete_note_title': 'Supprimer la note ?',
    'delete_note_body':
        'Cet élément ira dans la corbeille et sera supprimé après 30 jours.',
    'transcript_updated': 'Transcription mise à jour.',
    'transcription_failed': 'Échec de la transcription :',
    'could_not_play_audio': 'Impossible de lire l\'audio :',
    'note_deleted': 'Note supprimée.',
    'delete': 'Supprimer',
    'generate': 'Générer',
    'sign_in_cloud_hint':
        'Connexion requise pour le cloud. Enregistrement conservé localement.',
    'guest_note_saved': 'Note temporaire. Créez un compte pour la garder.',
    'required': 'Requis',
    'too_short': 'Trop court',
    'settings': 'Réglages',
    'mic_blocked_settings':
        'Micro bloqué. Activez-le dans Réglages pour enregistrer des notes vocales.',
    'mic_denied_settings':
        'Permission micro refusée. Activez-la dans Réglages.',
    'voice_input_notes_only':
        'La saisie vocale est disponible uniquement sur Notes vocales.',
    'recording_notes_only':
        'L\'enregistrement est disponible uniquement sur Notes vocales.',
    'could_not_start_recording': 'Impossible de démarrer l\'enregistrement :',
    'no_audio_file_saved':
        'Aucun fichier audio enregistré. Vérifiez la permission du micro.',
    'upload_failed_after_record':
        'Enregistrement traité, mais échec envoi/transcription :',
    'sign_in_to_upload':
        'Connectez-vous pour envoyer des enregistrements.',
    'audio_file_not_found': 'Fichier audio introuvable.',
    'recording_too_small':
        'Fichier trop petit. Le micro n\'a peut-être pas capté l\'audio.',
    'no_voice_detected':
        'Aucune voix détectée. Autorisez le micro et réessayez.',
    'transcript_not_generated': 'Impossible de générer la transcription.',
    'audio_saved_no_transcript':
        'Audio enregistré. Transcription impossible.',
    'upload_transcription_prefix': 'Envoi/transcription :',
    'audio_unavailable_device':
        'L\'audio n\'est plus disponible sur cet appareil.',
    'sign_in_to_save': 'Connectez-vous pour enregistrer des notes.',
    'no_internet_sync':
        'Pas d\'internet. La note se synchronisera plus tard.',
    'note_moved_recycle':
        'Note déplacée vers la corbeille. Conservée 30 jours.',
    'note_moved_recycle_named':
        '« {title} » déplacée vers la corbeille. Conservée 30 jours.',
    'cannot_delete_offline': 'Suppression impossible hors ligne.',
    'delete_failed': 'Échec de la suppression :',
    'delete_selected_title': 'Supprimer la sélection ?',
    'delete_notes_count': 'Supprimer {count}',
    'notes_deleted_count': '{count} note(s) supprimée(s).',
    'failed_to_delete': 'Échec de la suppression :',
    'transcript_empty': 'La transcription ne peut pas être vide.',
    'note_not_found': 'Note introuvable.',
    'transcript_saved_to': 'Transcription enregistrée dans {path}',
    'ai_tools': 'Outils IA',
    'summarize': 'Résumer',
    'qa_generator': 'Générateur Q&R',
    'study_buddy': 'Assistant d\'étude',
    'ask_about_document': 'Posez une question sur ce document...',
    'study_buddy_greeting':
        'Bonjour ! Posez-moi des questions sur cette transcription ou ce document.',
    'study_buddy_thinking': 'Réflexion...',
    'transcript_not_ready_chat':
        'La transcription n\'est pas encore prête. Attendez la fin du traitement.',
    'tab_transcript': 'Transcription',
    'tab_audio': 'Audio',
    'edit': 'Modifier',
    'updating': 'Mise à jour...',
    'update': 'Mettre à jour',
    'update_failed': 'Échec de la mise à jour :',
    'no_transcript_yet': 'Pas encore de transcription.',
    'voice_recording': 'Enregistrement vocal',
    'audio_gone_device': 'L\'audio n\'est plus sur cet appareil.',
    'no_audio_for_note': 'Aucun audio pour cette note.',
    'how_many_questions': 'Combien de questions ?',
    'cards_count': '{count} cartes',
    'record': 'Enregistrer',
    'recording_time_left': 'Enregistrement · {time} restant',
    'recording_audio_hint':
        'Enregistrement en cours · lecture après arrêt',
    'stop_recording': 'Arrêter l\'enregistrement',
    'processing_audio': 'Traitement audio...',
    'preparing_playback': 'Préparation de la lecture…',
    'transcription_failed_short': 'Échec de la transcription',
    'audio_saved_locally': 'Audio enregistré localement',
    'audio_saved_locally_error': 'Audio enregistré localement. {error}',
    'discard_recording_title': 'Abandonner l\'enregistrement ?',
    'discard_recording_body':
        'Cela supprimera l\'audio et la transcription.',
    'discard_recording_btn': 'Abandonner l\'enregistrement',
    'transcript_label': 'Transcription',
    'deselect': 'Tout désélectionner',
    'select_all': 'Tout sélectionner',
    'cancel_edit': 'Annuler la modification',
    'selected_count': '{count} sélectionnées',
    'chatbot_mic_menu_faqs':
        'Le micro du chatbot est disponible sur Menu et FAQ uniquement.',
    'speech_error': 'Erreur vocale :',
    'speech_not_available':
        'Reconnaissance vocale indisponible. Vérifiez les permissions.',
    'chatbot_greeting':
        'Bonjour ! Je suis l\'assistant Vox. Comment puis-je vous aider ?',
    'vox_assistant': 'Assistant Vox',
    'toggle_voice_output': 'Activer/désactiver la voix',
    'type_message': 'Tapez un message...',
    'keep': 'Garder',
    'listening_dots': 'Écoute...',
    'search_voice_listening': 'Parlez pour chercher...',
    'ask_something': 'Posez une question...',
    'stop_voice_output': 'Arrêter la voix',
  };

  static const Map<String, String> _ar = {
    'nav_home': 'الرئيسية',
    'nav_notes': 'الملاحظات',
    'nav_dictionary': 'القاموس',
    'nav_menu': 'القائمة',
    'section_account': 'الحساب',
    'section_app': 'التطبيق',
    'menu_profile': 'الملف الشخصي',
    'menu_language': 'اللغة',
    'menu_statistics': 'الإحصائيات',
    'menu_commands': 'الأوامر',
    'menu_about': 'من نحن',
    'menu_contact': 'اتصل بنا',
    'menu_logout': 'تسجيل الخروج',
    'guest': 'ضيف',
    'no_account': 'بدون حساب · البيانات غير محفوظة',
    'logout_title': 'تسجيل الخروج؟',
    'logout_body': 'بياناتك آمنة وستكون هنا عند عودتك.',
    'logout_cancel': 'إلغاء',
    'logout_confirm': 'خروج',
    'select_language': 'اختر اللغة',
    'search_hint': '...ابحث عن ملفات',
    'library': 'المكتبة',
    'tap_hint': 'اضغط للقراءة • اضغط مطولاً للحذف',
    'no_files': 'لا توجد ملفات.\nاضغط + للرفع.',
    'delete_confirm': 'حذف',
    'cancel': 'إلغاء',
    'deleted': 'تم الحذف',
    'remove_library': 'سيتم إزالته من مكتبتك.',
    'notes_title': 'الملاحظات',
    'voice_notes_title': 'ملاحظات صوتية',
    'title_hint': 'عنوان الملاحظة (اختياري)',
    'listening_title': '...جارٍ الاستماع للعنوان',
    'content_hint': '...تحدث أو اكتب ملاحظتك هنا',
    'saved_notes': 'الملاحظات المحفوظة',
    'save_note': 'حفظ الملاحظة',
    'clear': 'مسح',
    'note_saved': '!تم حفظ الملاحظة',
    'no_notes': '!لا توجد ملاحظات بعد. ابدأ بالتحدث أو الكتابة',
    'error_saving': ':خطأ في الحفظ',
    'add_content': 'يرجى إضافة محتوى قبل الحفظ.',
    'listening_content': 'جارٍ الاستماع بـ',
    'history_title': 'السجل',
    'history_empty': 'لا يوجد سجل بعد',
    'about_title': 'من نحن',
    'about_subtitle': 'VOX — قارئ بالأوامر الصوتية',
    'contact_title': 'اتصل بنا',
    'contact_subtitle': 'يسعدنا التواصل معك',
    'welcome_back': 'مرحباً بعودتك.',
    'welcome_back_user': 'مرحباً بعودتك، {name}.',
    'continuing_guest': 'المتابعة كضيف.',
    'device_recognized': 'تم التعرف على الجهاز.',
    'browser_recognized': 'تم التعرف على جلسة المتصفح.',
    'guest_badge': 'ضيف',
    'saved_badge': 'محفوظ',
    'discard': 'تجاهل',
    'update_note': 'تحديث الملاحظة',
    'recording_complete': 'اكتمل التسجيل',
    'save_note_list_hint': 'اضغط حفظ الملاحظة أدناه لإضافة هذا التسجيل إلى قائمتك.',
    'uploading_audio': 'جارٍ رفع الصوت...',
    'transcribing_audio': 'جارٍ تحويل الصوت إلى نص...',
    'transcription_complete': 'اكتملت التفريغ. راجع واحفظ ملاحظتك.',
    'mic_permission_required': 'إذن الميكروفون مطلوب للتسجيل.',
    'title_before_record': 'أضف عنواناً قبل التسجيل.',
    'record_before_save': 'سجّل صوتاً قبل الحفظ.',
    'title_before_save': 'أضف عنواناً قبل الحفظ.',
    'search_recordings': 'البحث في التسجيلات بالعنوان...',
    'transcript_edit_hint': 'يظهر النص هنا. يمكنك تعديله...',
    'note_title_field_hint': 'عنوان الملاحظة...',
    'delete_note_title': 'حذف الملاحظة؟',
    'delete_note_body': 'سيُنقل العنصر إلى سلة المحذوفات ويُحذف نهائياً بعد 30 يوماً.',
    'transcript_updated': 'تم تحديث النص.',
    'transcription_failed': 'فشل التفريغ:',
    'could_not_play_audio': 'تعذر تشغيل الصوت:',
    'note_deleted': 'تم حذف الملاحظة.',
    'delete': 'حذف',
    'generate': 'إنشاء',
    'sign_in_cloud_hint': 'يلزم تسجيل الدخول للسحابة. التسجيل محفوظ محلياً.',
    'guest_note_saved': 'حُفظت الملاحظة مؤقتاً. أنشئ حساباً للاحتفاظ بها.',
    'required': 'مطلوب',
    'too_short': 'قصير جداً',
    'settings': 'الإعدادات',
    'mic_blocked_settings':
        'الميكروفون محظور. فعّله في الإعدادات لتسجيل الملاحظات الصوتية.',
    'mic_denied_settings':
        'تم رفض إذن الميكروفون. فعّله في الإعدادات.',
    'voice_input_notes_only':
        'الإدخال الصوتي متاح فقط في شاشة الملاحظات الصوتية.',
    'recording_notes_only':
        'التسجيل متاح فقط في شاشة الملاحظات الصوتية.',
    'could_not_start_recording': 'تعذر بدء التسجيل:',
    'no_audio_file_saved':
        'لم يُحفظ ملف صوتي. تحقق من إذن الميكروفون وحاول مرة أخرى.',
    'upload_failed_after_record':
        'تمت معالجة التسجيل، لكن فشل الرفع/التفريغ:',
    'sign_in_to_upload': 'سجّل الدخول لرفع التسجيلات.',
    'audio_file_not_found': 'ملف الصوت غير موجود.',
    'recording_too_small':
        'ملف التسجيل صغير جداً. ربما لم يلتقط الميكروفون الصوت.',
    'no_voice_detected':
        'لم يُكتشف صوت. اسمح بالميكروفون وحاول مرة أخرى.',
    'transcript_not_generated': 'تعذر إنشاء النص.',
    'audio_saved_no_transcript': 'تم حفظ الصوت. تعذر إنشاء النص.',
    'upload_transcription_prefix': 'رفع/تفريغ:',
    'audio_unavailable_device': 'الصوت لم يعد متاحاً على هذا الجهاز.',
    'sign_in_to_save': 'سجّل الدخول لحفظ الملاحظات في حسابك.',
    'no_internet_sync': 'لا يوجد إنترنت. ستُزامَن الملاحظة عند الاتصال.',
    'note_moved_recycle':
        'نُقلت الملاحظة إلى سلة المحذوفات. تُحفظ 30 يوماً.',
    'note_moved_recycle_named':
        'نُقلت «{title}» إلى سلة المحذوفات. تُحفظ 30 يوماً.',
    'cannot_delete_offline': 'لا يمكن الحذف دون اتصال.',
    'delete_failed': 'فشل الحذف:',
    'delete_selected_title': 'حذف المحدد؟',
    'delete_notes_count': 'حذف {count}',
    'notes_deleted_count': 'تم حذف {count} ملاحظة.',
    'failed_to_delete': 'فشل الحذف:',
    'transcript_empty': 'لا يمكن أن يكون النص فارغاً.',
    'note_not_found': 'الملاحظة غير موجودة.',
    'transcript_saved_to': 'حُفظ النص في {path}',
    'ai_tools': 'أدوات الذكاء الاصطناعي',
    'summarize': 'تلخيص',
    'qa_generator': 'مولّد الأسئلة',
    'study_buddy': 'رفيق الدراسة',
    'ask_about_document': 'اسأل عن هذا المستند...',
    'study_buddy_greeting':
        'مرحباً! اسألني أي شيء عن هذا النص أو المستند.',
    'study_buddy_thinking': 'جارٍ التفكير...',
    'transcript_not_ready_chat':
        'النص غير جاهز بعد. انتظر حتى تنتهي عملية التفريغ.',
    'tab_transcript': 'النص',
    'tab_audio': 'الصوت',
    'edit': 'تعديل',
    'updating': 'جارٍ التحديث...',
    'update': 'تحديث',
    'update_failed': 'فشل التحديث:',
    'no_transcript_yet': 'لا يوجد نص بعد.',
    'voice_recording': 'تسجيل صوتي',
    'audio_gone_device': 'الصوت لم يعد على هذا الجهاز.',
    'no_audio_for_note': 'لا يوجد صوت لهذه الملاحظة.',
    'how_many_questions': 'كم عدد الأسئلة؟',
    'cards_count': '{count} بطاقات',
    'record': 'تسجيل',
    'recording_time_left': 'تسجيل · متبقي {time}',
    'recording_audio_hint': 'تسجيل الصوت · التشغيل بعد الإيقاف',
    'stop_recording': 'إيقاف التسجيل',
    'processing_audio': 'معالجة الصوت...',
    'preparing_playback': 'تحضير التشغيل…',
    'transcription_failed_short': 'فشل التفريغ',
    'audio_saved_locally': 'تم حفظ الصوت محلياً',
    'audio_saved_locally_error': 'تم حفظ الصوت محلياً. {error}',
    'discard_recording_title': 'تجاهل التسجيل؟',
    'discard_recording_body': 'سيُحذف الصوت والنص.',
    'discard_recording_btn': 'تجاهل التسجيل',
    'transcript_label': 'النص',
    'deselect': 'إلغاء التحديد',
    'select_all': 'تحديد الكل',
    'cancel_edit': 'إلغاء التعديل',
    'selected_count': '{count} محددة',
    'chatbot_mic_menu_faqs':
        'ميكروفون المساعد متاح في القائمة والأسئلة الشائعة فقط.',
    'speech_error': 'خطأ في الكلام:',
    'speech_not_available':
        'التعرف على الصوت غير متاح. تحقق من الأذونات.',
    'chatbot_greeting': 'مرحباً! أنا مساعد Vox. كيف يمكنني مساعدتك اليوم؟',
    'vox_assistant': 'مساعد Vox',
    'toggle_voice_output': 'تبديل الصوت',
    'type_message': 'اكتب رسالة...',
    'keep': 'إبقاء',
    'listening_dots': 'جارٍ الاستماع...',
    'search_voice_listening': 'تحدث للبحث...',
    'ask_something': 'اسأل شيئاً...',
    'stop_voice_output': 'إيقاف الصوت',
  };

  static const Map<String, String> _tr = {
    'nav_home': 'Ana Sayfa',
    'nav_notes': 'Notlar',
    'nav_dictionary': 'Sözlük',
    'nav_menu': 'Menü',
    'section_account': 'HESAP',
    'section_app': 'UYGULAMA',
    'menu_profile': 'Profil',
    'menu_language': 'Dil',
    'menu_statistics': 'İstatistikler',
    'menu_commands': 'Komutlar',
    'menu_about': 'Hakkımızda',
    'menu_contact': 'Bize Ulaşın',
    'menu_logout': 'Çıkış Yap',
    'guest': 'Misafir',
    'no_account': 'Hesap yok · veriler kaydedilmedi',
    'logout_title': 'Çıkış yapılsın mı?',
    'logout_body': 'Verileriniz güvende, döndüğünüzde burada olacak.',
    'logout_cancel': 'İptal',
    'logout_confirm': 'Çıkış Yap',
    'select_language': 'Dil Seç',
    'search_hint': 'Dosya ara...',
    'library': 'Kütüphane',
    'tap_hint': 'Okumak için dokun • Silmek için uzun bas',
    'no_files': 'Henüz dosya yok.\nYüklemek için + bas.',
    'delete_confirm': 'Sil',
    'cancel': 'İptal',
    'deleted': 'silindi',
    'remove_library': 'Bu, kütüphanenizden kaldırılacak.',
    'notes_title': 'Notlar',
    'voice_notes_title': 'Sesli Notlar',
    'title_hint': 'Not başlığı (isteğe bağlı)',
    'listening_title': 'Başlık dinleniyor...',
    'content_hint': 'Notunuzu buraya konuşun veya yazın...',
    'saved_notes': 'Kaydedilen Notlar',
    'save_note': 'Notu Kaydet',
    'clear': 'Temizle',
    'note_saved': 'Not kaydedildi!',
    'no_notes': 'Henüz not yok. Konuşmaya veya yazmaya başlayın!',
    'error_saving': 'Kaydetme hatası:',
    'add_content': 'Kaydetmeden önce içerik ekleyin.',
    'listening_content': 'Dinleniyor:',
    'history_title': 'Geçmiş',
    'history_empty': 'Henüz geçmiş yok',
    'about_title': 'Hakkımızda',
    'about_subtitle': 'VOX — Sesli Komut Okuyucu',
    'contact_title': 'Bize Ulaşın',
    'contact_subtitle': 'Sizden haber almak isteriz',
    'welcome_back': 'Tekrar hoş geldiniz.',
    'welcome_back_user': 'Tekrar hoş geldiniz, {name}.',
    'continuing_guest': 'Misafir olarak devam ediliyor.',
    'device_recognized': 'Cihaz tanındı.',
    'browser_recognized': 'Tarayıcı oturumu tanındı.',
    'guest_badge': 'MİSAFİR',
    'saved_badge': 'KAYITLI',
    'discard': 'Vazgeç',
    'update_note': 'Notu Güncelle',
    'recording_complete': 'Kayıt tamamlandı',
    'save_note_list_hint': 'Bu kaydı listeye eklemek için aşağıdan Notu Kaydet\'e dokunun.',
    'uploading_audio': 'Ses yükleniyor...',
    'transcribing_audio': 'Ses yazıya dönüştürülüyor...',
    'transcription_complete': 'Döküm tamam. Notunuzu gözden geçirip kaydedin.',
    'mic_permission_required': 'Kayıt için mikrofon izni gerekli.',
    'title_before_record': 'Kayıttan önce bir başlık ekleyin.',
    'record_before_save': 'Kaydetmeden önce ses kaydedin.',
    'title_before_save': 'Kaydetmeden önce bir başlık ekleyin.',
    'search_recordings': 'Kayıtlarda başlığa göre ara...',
    'transcript_edit_hint': 'Döküm burada görünür. Düzenleyebilirsiniz...',
    'note_title_field_hint': 'Not başlığı...',
    'delete_note_title': 'Not silinsin mi?',
    'delete_note_body':
        'Öğe Geri Dönüşüm Kutusu\'na gider ve 30 gün sonra kalıcı olarak silinir.',
    'transcript_updated': 'Döküm güncellendi.',
    'transcription_failed': 'Döküm başarısız:',
    'could_not_play_audio': 'Ses oynatılamadı:',
    'note_deleted': 'Not silindi.',
    'delete': 'Sil',
    'generate': 'Oluştur',
    'sign_in_cloud_hint':
        'Bulut için giriş gerekli. Kayıt yerelde tutuldu.',
    'guest_note_saved': 'Not geçici kaydedildi. Saklamak için hesap oluşturun.',
    'required': 'Zorunlu',
    'too_short': 'Çok kısa',
    'settings': 'Ayarlar',
    'mic_blocked_settings':
        'Mikrofon engellendi. Sesli notlar için Ayarlar\'dan etkinleştirin.',
    'mic_denied_settings':
        'Mikrofon izni reddedildi. Ayarlar\'dan etkinleştirin.',
    'voice_input_notes_only':
        'Ses girişi yalnızca Sesli Notlar ekranında kullanılabilir.',
    'recording_notes_only':
        'Kayıt yalnızca Sesli Notlar ekranında kullanılabilir.',
    'could_not_start_recording': 'Kayıt başlatılamadı:',
    'no_audio_file_saved':
        'Ses dosyası kaydedilmedi. Mikrofon iznini kontrol edip tekrar deneyin.',
    'upload_failed_after_record':
        'Kayıt işlendi ancak yükleme/döküm başarısız:',
    'sign_in_to_upload': 'Kayıtları yüklemek için hesabınızla giriş yapın.',
    'audio_file_not_found': 'Ses dosyası bulunamadı.',
    'recording_too_small':
        'Kayıt dosyası çok küçük. Mikrofon ses yakalamamış olabilir.',
    'no_voice_detected':
        'Ses algılanmadı. Mikrofona izin verip tekrar deneyin.',
    'transcript_not_generated': 'Döküm oluşturulamadı.',
    'audio_saved_no_transcript': 'Ses kaydedildi. Döküm oluşturulamadı.',
    'upload_transcription_prefix': 'Yükleme/döküm:',
    'audio_unavailable_device':
        'Ses artık bu cihazda kullanılamıyor.',
    'sign_in_to_save': 'Notları hesabınıza kaydetmek için giriş yapın.',
    'no_internet_sync':
        'İnternet yok. Not bağlantı gelince senkronize edilecek.',
    'note_moved_recycle':
        'Not Geri Dönüşüm Kutusu\'na taşındı. 30 gün saklanır.',
    'note_moved_recycle_named':
        '"{title}" Geri Dönüşüm Kutusu\'na taşındı. 30 gün saklanır.',
    'cannot_delete_offline': 'Çevrimdışıyken silinemez.',
    'delete_failed': 'Silme başarısız:',
    'delete_selected_title': 'Seçilenler silinsin mi?',
    'delete_notes_count': '{count} sil',
    'notes_deleted_count': '{count} not silindi.',
    'failed_to_delete': 'Silme başarısız:',
    'transcript_empty': 'Döküm boş olamaz.',
    'note_not_found': 'Not bulunamadı.',
    'transcript_saved_to': 'Döküm şuraya kaydedildi: {path}',
    'ai_tools': 'Yapay Zeka Araçları',
    'summarize': 'Özetle',
    'qa_generator': 'Soru-Cevap Oluşturucu',
    'study_buddy': 'Çalışma Arkadaşı',
    'ask_about_document': 'Bu belge hakkında sor...',
    'study_buddy_greeting':
        'Merhaba! Bu transkript veya belge hakkında bana soru sorabilirsin.',
    'study_buddy_thinking': 'Düşünüyor...',
    'transcript_not_ready_chat':
        'Transkript henüz hazır değil. Lütfen tamamlanmasını bekleyin.',
    'tab_transcript': 'Döküm',
    'tab_audio': 'Ses',
    'edit': 'Düzenle',
    'updating': 'Güncelleniyor...',
    'update': 'Güncelle',
    'update_failed': 'Güncelleme başarısız:',
    'no_transcript_yet': 'Henüz döküm yok.',
    'voice_recording': 'Ses Kaydı',
    'audio_gone_device': 'Ses artık bu cihazda yok.',
    'no_audio_for_note': 'Bu not için ses yok.',
    'how_many_questions': 'Kaç soru?',
    'cards_count': '{count} kart',
    'record': 'Kaydet',
    'recording_time_left': 'Kayıt · {time} kaldı',
    'recording_audio_hint':
        'Ses kaydediliyor · durdurunca oynatılır',
    'stop_recording': 'Kaydı Durdur',
    'processing_audio': 'Ses işleniyor...',
    'preparing_playback': 'Oynatma hazırlanıyor…',
    'transcription_failed_short': 'Döküm başarısız',
    'audio_saved_locally': 'Ses yerel olarak kaydedildi',
    'audio_saved_locally_error': 'Ses yerel olarak kaydedildi. {error}',
    'discard_recording_title': 'Kayıt silinsin mi?',
    'discard_recording_body': 'Bu, sesi ve dökümü silecek.',
    'discard_recording_btn': 'Kaydı sil',
    'transcript_label': 'Döküm',
    'deselect': 'Seçimi kaldır',
    'select_all': 'Tümünü seç',
    'cancel_edit': 'Düzenlemeyi iptal et',
    'selected_count': '{count} seçili',
    'chatbot_mic_menu_faqs':
        'Sohbet botu mikrofonu yalnızca Menü ve SSS\'de kullanılabilir.',
    'speech_error': 'Konuşma hatası:',
    'speech_not_available':
        'Konuşma tanıma kullanılamıyor. İzinleri kontrol edin.',
    'chatbot_greeting':
        'Merhaba! Ben Vox Asistanı. Bugün size nasıl yardımcı olabilirim?',
    'vox_assistant': 'Vox Asistanı',
    'toggle_voice_output': 'Sesi aç/kapat',
    'type_message': 'Bir mesaj yazın...',
    'keep': 'Sakla',
    'listening_dots': 'Dinleniyor...',
    'search_voice_listening': 'Aramak için konuşun...',
    'ask_something': 'Bir şey sorun...',
    'stop_voice_output': 'Sesi durdur',
  };

  static const Map<String, String> _zh = {
    'nav_home': '首页',
    'nav_notes': '笔记',
    'nav_dictionary': '词典',
    'nav_menu': '菜单',
    'section_account': '账户',
    'section_app': '应用',
    'menu_profile': '个人资料',
    'menu_language': '语言',
    'menu_statistics': '统计',
    'menu_commands': '指令',
    'menu_about': '关于我们',
    'menu_contact': '联系我们',
    'menu_logout': '退出登录',
    'guest': '访客',
    'no_account': '未登录 · 数据未保存',
    'logout_title': '退出登录？',
    'logout_body': '您的数据安全，回来后仍在这里。',
    'logout_cancel': '取消',
    'logout_confirm': '退出',
    'select_language': '选择语言',
    'search_hint': '搜索文件...',
    'library': '图书馆',
    'tap_hint': '点击阅读 • 长按删除',
    'no_files': '暂无文件。\n点击 + 上传。',
    'delete_confirm': '删除',
    'cancel': '取消',
    'deleted': '已删除',
    'remove_library': '这将从您的图书馆中移除。',
    'notes_title': '笔记',
    'voice_notes_title': '语音笔记',
    'title_hint': '笔记标题（可选）',
    'listening_title': '正在听取标题...',
    'content_hint': '在此处说话或输入笔记...',
    'saved_notes': '已保存的笔记',
    'save_note': '保存笔记',
    'clear': '清除',
    'note_saved': '笔记已保存！',
    'no_notes': '暂无笔记，开始说话或输入吧！',
    'error_saving': '保存错误：',
    'add_content': '请在保存前添加内容。',
    'listening_content': '正在用以下语言听取：',
    'history_title': '历史记录',
    'history_empty': '暂无历史记录',
    'about_title': '关于我们',
    'about_subtitle': 'VOX — 语音指令阅读器',
    'contact_title': '联系我们',
    'contact_subtitle': '我们期待您的来信',
    'welcome_back': '欢迎回来。',
    'welcome_back_user': '欢迎回来，{name}。',
    'continuing_guest': '以访客身份继续。',
    'device_recognized': '已识别设备。',
    'browser_recognized': '已识别浏览器会话。',
    'guest_badge': '访客',
    'saved_badge': '已保存',
    'discard': '丢弃',
    'update_note': '更新笔记',
    'recording_complete': '录音完成',
    'save_note_list_hint': '点击下方保存笔记，将此录音加入列表。',
    'uploading_audio': '正在上传音频...',
    'transcribing_audio': '正在转写音频...',
    'transcription_complete': '转写完成。请检查并保存笔记。',
    'mic_permission_required': '录音需要麦克风权限。',
    'title_before_record': '录音前请添加标题。',
    'record_before_save': '保存前请先录音。',
    'title_before_save': '保存前请添加标题。',
    'search_recordings': '按标题搜索录音...',
    'transcript_edit_hint': '转写文本显示在此，可编辑...',
    'note_title_field_hint': '笔记标题...',
    'delete_note_title': '删除笔记？',
    'delete_note_body': '该项目将移入回收站，30天后永久删除。',
    'transcript_updated': '转写已更新。',
    'transcription_failed': '转写失败：',
    'could_not_play_audio': '无法播放音频：',
    'note_deleted': '笔记已删除。',
    'delete': '删除',
    'generate': '生成',
    'sign_in_cloud_hint': '云上传/转写需要登录。录音已保存在本地。',
    'guest_note_saved': '笔记已临时保存。创建账户以保留。',
    'required': '必填',
    'too_short': '太短',
    'settings': '设置',
    'mic_blocked_settings': '麦克风被阻止。请在设置中启用以录制语音笔记。',
    'mic_denied_settings': '麦克风权限被拒绝。请在设置中启用。',
    'voice_input_notes_only': '语音输入仅在语音笔记页面可用。',
    'recording_notes_only': '录音仅在语音笔记页面可用。',
    'could_not_start_recording': '无法开始录音：',
    'no_audio_file_saved': '未保存音频文件。请检查麦克风权限后重试。',
    'upload_failed_after_record': '录音已处理，但上传/转写失败：',
    'sign_in_to_upload': '请登录账户以上传录音。',
    'audio_file_not_found': '未找到音频文件。',
    'recording_too_small': '录音文件过小，麦克风可能未捕获声音。',
    'no_voice_detected': '未检测到语音。请允许麦克风后重试。',
    'transcript_not_generated': '无法生成转写文本。',
    'audio_saved_no_transcript': '音频已保存，但无法生成转写。',
    'upload_transcription_prefix': '上传/转写：',
    'audio_unavailable_device': '此设备上已无该音频。',
    'sign_in_to_save': '请登录以将笔记保存到账户。',
    'no_internet_sync': '无网络。联网后将同步笔记。',
    'note_moved_recycle': '笔记已移至回收站，保留30天。',
    'note_moved_recycle_named': '「{title}」已移至回收站，保留30天。',
    'cannot_delete_offline': '离线时无法删除。',
    'delete_failed': '删除失败：',
    'delete_selected_title': '删除所选？',
    'delete_notes_count': '删除 {count} 项',
    'notes_deleted_count': '已删除 {count} 条笔记。',
    'failed_to_delete': '删除失败：',
    'transcript_empty': '转写文本不能为空。',
    'note_not_found': '未找到笔记。',
    'transcript_saved_to': '转写已保存至 {path}',
    'ai_tools': 'AI 工具',
    'summarize': '摘要',
    'qa_generator': '问答生成器',
    'study_buddy': '学习助手',
    'ask_about_document': '询问此文档...',
    'study_buddy_greeting': '你好！可以问我关于此转录或文档的任何问题。',
    'study_buddy_thinking': '思考中...',
    'transcript_not_ready_chat': '转录尚未完成，请等待处理结束。',
    'tab_transcript': '转写',
    'tab_audio': '音频',
    'edit': '编辑',
    'updating': '更新中...',
    'update': '更新',
    'update_failed': '更新失败：',
    'no_transcript_yet': '尚无转写文本。',
    'voice_recording': '语音录音',
    'audio_gone_device': '此设备上已无该音频文件。',
    'no_audio_for_note': '此笔记无可用音频。',
    'how_many_questions': '多少个问题？',
    'cards_count': '{count} 张卡片',
    'record': '录音',
    'recording_time_left': '录音中 · 剩余 {time}',
    'recording_audio_hint': '正在录音 · 停止后可播放',
    'stop_recording': '停止录音',
    'processing_audio': '正在处理音频...',
    'preparing_playback': '正在准备播放…',
    'transcription_failed_short': '转写失败',
    'audio_saved_locally': '音频已本地保存',
    'audio_saved_locally_error': '音频已本地保存。{error}',
    'discard_recording_title': '丢弃录音？',
    'discard_recording_body': '这将删除音频和转写文本。',
    'discard_recording_btn': '丢弃录音',
    'transcript_label': '转写',
    'deselect': '取消全选',
    'select_all': '全选',
    'cancel_edit': '取消编辑',
    'selected_count': '已选 {count} 项',
    'chatbot_mic_menu_faqs': '聊天机器人麦克风仅在菜单和常见问题页面可用。',
    'speech_error': '语音错误：',
    'speech_not_available': '语音识别不可用。请检查权限。',
    'chatbot_greeting': '你好！我是 Vox 助手。今天我能帮你什么？',
    'vox_assistant': 'Vox 助手',
    'toggle_voice_output': '切换语音输出',
    'type_message': '输入消息...',
    'keep': '保留',
    'listening_dots': '正在聆听...',
    'search_voice_listening': '说话即可搜索...',
    'ask_something': '问点什么...',
    'stop_voice_output': '停止语音',
  };
}
