// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwAxySSdcWdjjDR5cuqP8WVOcsMxToT5A',
    appId: '1:1033671503358:web:ade37f795afeedf7fca4af',
    messagingSenderId: '1033671503358',
    projectId: 'my-vox-app',
    authDomain: 'my-vox-app.firebaseapp.com',
    storageBucket: 'my-vox-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0VlHzYXIOUOJTkm5mo-fO5-QvdTtxmFw',
    appId: '1:1033671503358:android:4050ec41e8bed73bfca4af',
    messagingSenderId: '1033671503358',
    projectId: 'my-vox-app',
    storageBucket: 'my-vox-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmb-sI-nnrFsaQWKIdT39UkdBH6fHBii0',
    appId: '1:1033671503358:ios:a7eb2c1bf8f103a0fca4af',
    messagingSenderId: '1033671503358',
    projectId: 'my-vox-app',
    storageBucket: 'my-vox-app.firebasestorage.app',
    iosBundleId: 'com.example.voxapplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmb-sI-nnrFsaQWKIdT39UkdBH6fHBii0',
    appId: '1:1033671503358:ios:a7eb2c1bf8f103a0fca4af',
    messagingSenderId: '1033671503358',
    projectId: 'my-vox-app',
    storageBucket: 'my-vox-app.firebasestorage.app',
    iosBundleId: 'com.example.voxapplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwAxySSdcWdjjDR5cuqP8WVOcsMxToT5A',
    appId: '1:1033671503358:web:866ef67554653262fca4af',
    messagingSenderId: '1033671503358',
    projectId: 'my-vox-app',
    authDomain: 'my-vox-app.firebaseapp.com',
    storageBucket: 'my-vox-app.firebasestorage.app',
  );
}