// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYO2N189vadDto8I2wOdfiquhfG15oVG4',
    appId: '1:650391636557:web:5f1fa32c9341beea10ea04',
    messagingSenderId: '650391636557',
    projectId: 'the-vox-application',
    authDomain: 'the-vox-application.firebaseapp.com',
    databaseURL: 'https://the-vox-application-default-rtdb.firebaseio.com',
    storageBucket: 'the-vox-application.firebasestorage.app',
    measurementId: 'G-Q5B06K52VG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVLxpPN6CV3T_fkG7nK20WcRKxAhcqXqU',
    appId: '1:650391636557:android:061cb13b6de1461b10ea04',
    messagingSenderId: '650391636557',
    projectId: 'the-vox-application',
    databaseURL: 'https://the-vox-application-default-rtdb.firebaseio.com',
    storageBucket: 'the-vox-application.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCD0Xs0XLcjQyCZ7le0etwZzLib1Z4Urw',
    appId: '1:650391636557:ios:e928e402888ac69210ea04',
    messagingSenderId: '650391636557',
    projectId: 'the-vox-application',
    databaseURL: 'https://the-vox-application-default-rtdb.firebaseio.com',
    storageBucket: 'the-vox-application.firebasestorage.app',
    iosClientId: '650391636557-ahl0b6bvceqtcg6p47p2e5svt9v6dqdm.apps.googleusercontent.com',
    iosBundleId: 'com.example.voxapplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCD0Xs0XLcjQyCZ7le0etwZzLib1Z4Urw',
    appId: '1:650391636557:ios:e928e402888ac69210ea04',
    messagingSenderId: '650391636557',
    projectId: 'the-vox-application',
    databaseURL: 'https://the-vox-application-default-rtdb.firebaseio.com',
    storageBucket: 'the-vox-application.firebasestorage.app',
    iosClientId: '650391636557-ahl0b6bvceqtcg6p47p2e5svt9v6dqdm.apps.googleusercontent.com',
    iosBundleId: 'com.example.voxapplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYO2N189vadDto8I2wOdfiquhfG15oVG4',
    appId: '1:650391636557:web:049fb2d56fe179c110ea04',
    messagingSenderId: '650391636557',
    projectId: 'the-vox-application',
    authDomain: 'the-vox-application.firebaseapp.com',
    databaseURL: 'https://the-vox-application-default-rtdb.firebaseio.com',
    storageBucket: 'the-vox-application.firebasestorage.app',
    measurementId: 'G-SFT2TH0PY4',
  );

}